[mapelement_0]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_1]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_2]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_3]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_4]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_5]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_6]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_7]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_8]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_9]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_10]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_11]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_12]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_13]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_14]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_15]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_16]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_17]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_18]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_19]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_20]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_21]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_22]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_23]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_24]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_25]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_26]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_27]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_28]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_29]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_30]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_31]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_32]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_33]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_34]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_35]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_36]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_37]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_38]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_39]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_40]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_41]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_42]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_43]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_44]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_45]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_46]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_47]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_48]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_49]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_50]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_51]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_52]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_53]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_54]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_55]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_56]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_57]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_58]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_59]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_60]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_61]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_62]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_63]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_64]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_65]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_66]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_67]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_68]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_69]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_70]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_71]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_72]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_73]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_74]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_75]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_76]
text=Exit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_77]
text=East Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_78]
text=West Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_79]
text=Soul Obelisk
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_80]
text=Entrance
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_81]
text=Exit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_82]
text=Lumbridge
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_83]
text=Varrock
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_84]
text=Kingdom of<br>Misthalin
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_85]
text=Al Kharid
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_86]
text=Duel<br>Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_87]
text=Shantay<br>Pass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_88]
text=Toll<br>Gate
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_89]
text=Tutorial Island
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_90]
text=Port<br>Sarim
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_91]
text=Falador
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_92]
text=Edgeville
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_93]
text=Brimhaven
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_94]
text=Karamja
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_95]
text=Crandor
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_96]
text=Entrana
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_97]
text=Draynor<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_98]
text=Jail
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_99]
text=Market
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_100]
text=Draynor Manor
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_101]
text=Barbarian<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_102]
text=Desert Mining<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_103]
text=Bedabin<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_104]
text=Exam Centre
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_105]
text=Digsite
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_106]
text=Lumber Yard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_107]
text=Palace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_108]
text=Cooks'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_109]
text=Monastery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_110]
text=Dwarven<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_111]
text=Ice<br>Mountain
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_112]
text=Black Knights'<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_113]
text=Goblin<br>Village
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_114]
text=White Knights'<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_115]
text=Park
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_116]
text=Kingdom of<br>Asgarnia
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_117]
text=Dark Wizards'<br>Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_118]
text=Slayer<br>Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_119]
text=Melzar's<br>Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_120]
text=Rimmington
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_121]
text=Wizards' Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_122]
text=Lumbridge<br>Swamp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_123]
text=Fishing<br>Platform
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_124]
text=Tai Bwo Wannai
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_125]
text=Shilo Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_126]
text=Shipyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_127]
text=Cairn Isle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_128]
text=Kharazi Jungle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_129]
text=Chaos<br>Temple
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_130]
text=Graveyard of<br>Shadows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_131]
text=Bandit<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_132]
text=Dark Warriors'<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_133]
text=Ruins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_134]
text=The Forgotten<br>Cemetery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_135]
text=Red Dragon<br>Isle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_136]
text=Wilderness
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_137]
text=Lava Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_138]
text=Frozen Waste<br>Plateau
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_139]
text=Agility Training<br>Area
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_140]
text=Pirates'<br>Hideout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_141]
text=Mage Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_142]
text=Deserted<br>Keep
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_143]
text=Scorpion<br>Pit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_144]
text=Rogues' Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_145]
text=Demonic<br>Ruins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_146]
text=Heroes'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_147]
text=Druids'<br>Circle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_148]
text=Taverley
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_149]
text=White Wolf<br>Mountain
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_150]
text=Catherby
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_151]
text=Camelot<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_152]
text=Seers'<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_153]
text=Sinclair Mansion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_154]
text=Flax
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_155]
text=Beehives
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_156]
text=Sorcerer's Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_157]
text=Keep<br>Le Faye
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_158]
text=Legends'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_159]
text=Hemenster
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_160]
text=McGrubor's<br>Wood
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_161]
text=Coal<br>Trucks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_162]
text=Fishing<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_163]
text=Kingdom of<br>Kandarin
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_164]
text=East<br>Ardougne
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_165]
text=West<br>Ardougne
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_166]
text=Ardougne<br>Sewers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_167]
text=Combat<br>Training<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_168]
text=Tree Gnome<br>Stronghold
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_169]
text=Grand Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_170]
text=Swamp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_171]
text=Gnome Ball<br>Field
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_172]
text=Barbarian<br>Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_173]
text=Underground<br>Pass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_174]
text=Battlefield
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_175]
text=Baxtorian<br>Falls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_176]
text=Tree Gnome<br>Village
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_177]
text=Fight<br>Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_178]
text=Port<br>Khazard
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_179]
text=Yanille
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_180]
text=Wizards'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_181]
text=Observatory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_182]
text=Necromancer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_183]
text=Gu'Tanoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_184]
text=Feldip<br>Hills
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_185]
text=Ardougne<br>Zoo
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_186]
text=Morytania
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_187]
text=Mort Myre<br>Swamp
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_188]
text=Canifis
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_189]
text=River<br>Salve
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_190]
text=River Lum
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_191]
text=Temple
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_192]
text=Agility<br>Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_193]
text=Burthorpe
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_194]
text=Death<br>Plateau
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_195]
text=Tirannwn
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_196]
text=Isafdar
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_197]
text=Arandar
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_198]
text=Prifddinas
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_199]
text=Tyras<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_200]
text=Elf<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_201]
text=Trollheim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_202]
text=Troll<br>Stronghold
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_203]
text=Mort'ton
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_204]
text=The<br>Hollows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_205]
text=Poison Waste
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_206]
text=Castle Wars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_207]
text=Champions'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_208]
text=Rellekka
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_209]
text=Golden<br>Apple Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_210]
text=Lighthouse
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_211]
text=Fremennik<br>Province
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_212]
text=Crafting<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_213]
text=Haunted<br>Woods
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_214]
text=Miscellania
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_215]
text=Etceteria
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_216]
text=Ape Atoll
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_217]
text=Crash<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_218]
text=Marim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_219]
text=Fenkenstrain's<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_220]
text=Mausoleum
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_221]
text=Trollweiss<br>Mountain
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_222]
text=Abandoned<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_223]
text=Ruins of<br>Uzer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_224]
text=River<br>Elid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_225]
sprite="mapfunction_sep,96"
category=category_1240
mapfunction=yes
show=both

[mapelement_226]
text=Pollnivneach
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_227]
text=Pyramid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_228]
text=Menaphos
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_229]
text=Sophanem
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_230]
text=Agility<br>Pyramid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_231]
text=Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_232]
text=Port<br>Phasmatys
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_233]
text=Ectofuntus
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_234]
text=Mountain<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_235]
text=Kharidian<br>Desert
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_236]
text=Ice Path
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_237]
text=Barrows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_238]
text=Jiggig
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_239]
text=Mudskipper<br>Point
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_240]
text=Nardah
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_241]
text=Mage<br>Training<br>Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_242]
text=Keldagrim<br>Entrance
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_243]
text=Waterbirth<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_244]
text=Lletya
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_245]
text=Burgh de Rott
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_246]
text=Lizards
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_247]
text=Quarry
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_248]
text=Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_249]
text=Mos Le'Harmless
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_250]
text=Distilleries
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_251]
text=Ranging<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_252]
text=Dragontooth<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_253]
text=Piscatoris<br>Fishing<br>Colony
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_254]
text=Here Be<br>Penguins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_255]
text=Void Knights'<br>Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_256]
text=Lunar Isle
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_257]
text=Pirates' Cove
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_258]
text=Vultures
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_259]
text=Port<br>Tyras
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_260]
text=Castle<br>Drakan
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_261]
text=Sanguinesti<br>Region
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_262]
text=Meiyerditch
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_263]
text=Witchaven
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_264]
text=Warriors'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_265]
text=Musa Point
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_266]
text=Eagles'<br>Peak
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_267]
text=Falconer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_268]
text=Barbarian<br>Assault
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_269]
text=Iceberg
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_270]
text=Pest<br>Control
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_271]
text=Neitiznot
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_272]
text=Jatizso
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_273]
text=Fremennik Isles
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_274]
text=Tower of<br>Life
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_275]
text=Clocktower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_276]
text=Harmony
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_277]
text=Trawler
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_278]
text=Otto's<br>Grotto
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_279]
text=Party Room
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_280]
text=Courthouse
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_281]
text=God Wars<br>Dungeon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_282]
text=Wilderness<br>Volcano
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_283]
text=Clan Wars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_284]
text=Grand Exchange
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_285]
text=Oo'glog
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_286]
text=Fist of Guthix
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_287]
text=Stealing Creation
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_288]
text=Soul Wars
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_289]
text=Queen's<br>Chamber
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_290]
text=Soldiers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_291]
text=Guardians
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_292]
text=Ice Queen's<br>Lair
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_293]
text=Fountain<br>of Heroes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_294]
text=Mountain<br>dwarves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_295]
text=Nora T. Hagg's<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_296]
text=Salarin the<br>Twisted
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_297]
text=H.A.M. Cult
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_298]
text=Draynor Sewers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_299]
text=Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_300]
text=Watermill<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_301]
text=Champions'<br>Challenge
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_302]
text=Draynor Manor<br>basement
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_303]
text=VTAM Corporation
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_304]
text=Bank vault
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_305]
text=Goblin Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_306]
text=Chasm of<br>Tears
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_307]
text=Tears of<br>Guthix
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_308]
text=Lumbridge<br>Castle<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_309]
text=Giant frogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_310]
text=Hill giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_311]
text=Chronozon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_312]
text=Here be<br>dead stuff
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_313]
text=Thugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_314]
text=Dave's<br>Basement<br>of Doom
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_315]
text=Poison spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_316]
text=Poison<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_317]
text=Zombies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_318]
text=Zombies & rocks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_319]
text=Skeletons<br>& zombies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_320]
text=Earth warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_321]
text=Earth<br>warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_322]
text=Skeletons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_323]
text=Black demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_324]
text=Black<br>demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_325]
text=Chaos<br>druids
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_326]
text=Hobgoblins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_327]
text=Red spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_328]
text=Red<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_329]
text=Rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_330]
text=Banshees
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_331]
text=Kurask
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_332]
text=Cave crawlers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_333]
text=Turoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_334]
text=Basilisks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_335]
text=Aberrant<br>spectres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_336]
text=Rock<br>slugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_337]
text=Cockatrice
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_338]
text=Pyrefiends
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_339]
text=Jellies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_340]
text=Throne room
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_341]
text=Beware of the<br>mushrooms
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_342]
text=Shrine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_343]
text=Otherworldly<br>beings
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_344]
text=Puro-puro
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_345]
text=Moss giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_346]
text=Moss<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_347]
text=Dogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_348]
text=Fire<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_349]
text=Red dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_350]
text=Bronze<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_351]
text=Iron & steel<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_352]
text=Greater demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_353]
text=Agility Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_354]
text=Jogres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_355]
text=Elvarg
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_356]
text=Lesser demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_357]
text=Gift of<br>Peace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_358]
text=Grain of<br>Plenty
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_359]
text=Box of<br>Health
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_360]
text=Cradle of<br>Life
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_361]
text=Crypt<br>rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_362]
text=Dungeon<br>rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_363]
text=Nechryael
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_364]
text=Dagannoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_365]
text=Infernal<br>magi
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_366]
text=Dragons & fire<br>elementals
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_367]
text=Dust<br>devils
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_368]
text=Waterfiends
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_369]
text=Rock<br>crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_370]
text=Ice<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_371]
text=Zamorak<br>fighters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_372]
text=Cave<br>bugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_373]
text=Shadow<br>hounds &<br>wolves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_374]
text=Dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_375]
text=Giant<br>ants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_376]
text=Spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_377]
text=Shadow<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_378]
text=Crypt & shadow<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_379]
text=Leeches
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_380]
text=Ice warriors<br>& giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_381]
text=Gargoyles
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_382]
text=Trolls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_383]
text=Ice trolls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_384]
text=Monks of<br>Zamorak
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_385]
text=Mummies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_386]
text=Zombies,<br>skeletons &<br>animated<br>items
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_387]
text=Fight Pit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_388]
text=Fight Cave
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_389]
text=Library
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_390]
text=Terror dogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_391]
text=Anger
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_392]
text=Hopelessness
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_393]
text=Confusion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_394]
text=Fear
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_395]
text=Saradomin's<br>Encampment
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_396]
text=Zamorak's<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_397]
text=Armadyl's<br>Eyrie
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_398]
text=Bandos's<br>Stronghold
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_399]
text=Distillery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_400]
text=Dead people
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_401]
text=Nothing<br>interesting<br>happens<br>here
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_402]
text=Beware of<br>the scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_403]
text=Mining Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_404]
text=Access to<br>Falador
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_405]
text=Hammerspike's<br>hangout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_406]
text=Pickaxe<br>factory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_407]
text=Boot
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_408]
text=River Kelda
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_409]
text=Dondakan's<br>rock
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_410]
text=Minecarts
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_411]
text=Blast<br>Furnace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_412]
text=Brewery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_413]
text=Agility course
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_414]
text=Wire<br>machine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_415]
text=Bone<br>collector
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_416]
text=Oldak's<br>teleportation<br>laboratory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_417]
text=Station
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_418]
text=Council<br>chamber
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_419]
text=Ur-tag
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_420]
text=Ur-meg
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_421]
text=Ur-zek & Ur-taal
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_422]
text=Tegdak
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_423]
text=Ur-vass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_424]
text=Nursery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_425]
text=Cauldron of<br>Thunder
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_426]
text=Black Knights'<br>Base
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_427]
text=Hellhounds
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_428]
text=Fire Obelisk
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_429]
text=Black dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_430]
text=Black<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_431]
text=Dramen Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_432]
text=Animated<br>axes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_433]
text=Chaos<br>dwarves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_434]
text=Blue<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_435]
text=Poisonous<br>scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_436]
text=Agility<br>course<br>spikes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_437]
text=Mage Arena<br>bank
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_438]
text=King<br>Black<br>Dragon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_439]
text=Shadow<br>warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_440]
text=Pit scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_441]
text=Rat Pits
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_442]
text=Bats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_443]
text=Ogres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_444]
text=Here be<br>goblins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_445]
text=Skeletal wyverns
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_446]
text=Pirates
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_447]
text=Muggers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_448]
text=Black<br>Guard<br>H.Q.
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_449]
text=Zanik's<br>bedroom
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_450]
text=Essence<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_451]
text=Miscellania<br>Expansion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_452]
text=Sea snakes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_453]
text=Altar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_454]
text=Lizards &<br>Zamorak fighters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_455]
text=Goutweed<br>store
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_456]
text=Troll<br>generals
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_457]
text=Kitchen
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_458]
text=Tanglefeet
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_459]
text=Giant rock crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_460]
text=Giant<br>rock crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_461]
text=Rock lobsters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_462]
text=Rock<br>lobsters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_463]
text=Wallasalki
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_464]
text=Dagannoth<br>Kings
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_465]
text=Volcano
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_466]
text=Cave horrors<br>&<br>albino bats
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_467]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_468]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_469]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_470]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_471]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_472]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_473]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_474]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_475]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_476]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_477]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_478]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_479]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_480]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_481]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_482]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_483]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_484]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_485]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_486]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_487]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_488]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_489]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_490]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_491]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_492]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_493]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_494]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_495]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_496]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_497]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_498]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_499]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_500]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_501]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_502]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_503]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_504]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_505]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_506]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_507]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_508]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_509]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_510]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_511]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_512]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_513]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_514]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_515]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_516]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_517]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_518]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_519]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_520]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_521]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_522]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_523]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_524]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_525]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_526]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_527]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_528]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_529]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_530]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_531]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_532]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_533]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_534]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_535]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_536]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_537]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_538]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_539]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_540]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_541]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_542]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_543]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_544]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_545]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_546]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_547]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_548]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_549]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_550]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_551]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_552]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_553]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_554]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_555]
sprite="mapfunction_sep,0"
category=category_951
mapfunction=yes
show=both

[mapelement_556]
sprite="mapfunction_sep,1"
category=category_952
mapfunction=yes
show=both

[mapelement_557]
sprite="mapfunction_sep,2"
category=category_953
mapfunction=yes
show=both

[mapelement_558]
sprite="mapfunction_sep,3"
category=category_954
mapfunction=yes
show=both

[mapelement_559]
sprite="mapfunction_sep,4"
category=category_955
mapfunction=yes
show=both

[mapelement_560]
sprite="mapfunction_sep,5"
category=category_1156
mapfunction=yes
show=both

[mapelement_561]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both

[mapelement_562]
sprite="mapfunction_sep,7"
category=category_1158
mapfunction=yes
show=both

[mapelement_563]
sprite="mapfunction_sep,8"
category=category_1159
mapfunction=yes
show=both

[mapelement_564]
sprite="mapfunction_sep,9"
category=category_1160
mapfunction=yes
show=both

[mapelement_565]
sprite="mapfunction_sep,10"
category=category_1161
mapfunction=yes
show=both

[mapelement_566]
sprite="mapfunction_sep,11"
category=category_1162
mapfunction=yes
show=both

[mapelement_567]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=both

[mapelement_568]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=minimap

[mapelement_569]
sprite="mapfunction_sep,13"
category=category_1163
mapfunction=yes
show=both

[mapelement_570]
sprite="mapfunction_sep,14"
category=category_1164
mapfunction=yes
show=both

[mapelement_571]
sprite="mapfunction_sep,15"
category=category_1165
mapfunction=yes
show=both

[mapelement_572]
sprite="mapfunction_sep,16"
category=category_1166
mapfunction=yes
show=both

[mapelement_573]
sprite="mapfunction_sep,17"
category=category_1167
mapfunction=yes
show=both

[mapelement_574]
sprite="mapfunction_sep,18"
category=category_1168
mapfunction=yes
show=both

[mapelement_575]
sprite="mapfunction_sep,19"
category=category_1169
mapfunction=yes
show=both

[mapelement_576]
sprite="mapfunction_sep,20"
category=category_1170
mapfunction=yes
show=both

[mapelement_577]
sprite="mapfunction_sep,21"
category=category_1171
mapfunction=yes
show=both

[mapelement_578]
sprite="mapfunction_sep,22"
category=category_1172
mapfunction=yes
show=both

[mapelement_579]
sprite="mapfunction_sep,23"
category=category_1173
mapfunction=yes
show=both

[mapelement_580]
sprite="mapfunction_sep,24"
category=category_1174
mapfunction=yes
show=both

[mapelement_581]
sprite="mapfunction_sep,25"
category=category_1175
mapfunction=yes
show=both

[mapelement_582]
sprite="mapfunction_sep,26"
category=category_1176
mapfunction=yes
show=both

[mapelement_583]
sprite="mapfunction_sep,27"
category=category_1177
mapfunction=yes
show=both

[mapelement_584]
sprite="mapfunction_sep,28"
category=category_1178
mapfunction=yes
show=both

[mapelement_585]
sprite="mapfunction_sep,29"
category=category_1179
mapfunction=yes
show=both

[mapelement_586]
sprite="mapfunction_sep,30"
category=category_1180
mapfunction=yes
show=both

[mapelement_587]
sprite="mapfunction_sep,31"
category=category_1181
mapfunction=yes
show=both

[mapelement_588]
sprite="mapfunction_sep,32"
category=category_1182
mapfunction=yes
show=both

[mapelement_589]
sprite="mapfunction_sep,33"
category=category_1183
mapfunction=yes
show=both

[mapelement_590]
sprite="mapfunction_sep,34"
category=category_1184
mapfunction=yes
show=both

[mapelement_591]
sprite="mapfunction_sep,35"
category=category_1185
mapfunction=yes
show=both

[mapelement_592]
sprite="mapfunction_sep,36"
category=category_1186
mapfunction=yes
show=both

[mapelement_593]
sprite="mapfunction_sep,37"
category=category_1187
mapfunction=yes
show=both

[mapelement_594]
sprite="mapfunction_sep,38"
category=category_1188
mapfunction=yes
show=both

[mapelement_595]
sprite="mapfunction_sep,39"
category=category_1189
mapfunction=yes
show=both

[mapelement_596]
sprite="mapfunction_sep,40"
category=category_1190
mapfunction=yes
show=both

[mapelement_597]
sprite="mapfunction_sep,41"
category=category_1191
mapfunction=yes
show=both

[mapelement_598]
sprite="mapfunction_sep,42"
category=category_1192
mapfunction=yes
show=both

[mapelement_599]
sprite="mapfunction_sep,43"
category=category_1193
mapfunction=yes
show=both

[mapelement_600]
sprite="mapfunction_sep,44"
category=category_1194
mapfunction=yes
show=both

[mapelement_601]
sprite="mapfunction_sep,45"
category=category_1195
mapfunction=yes
show=both

[mapelement_602]
sprite="mapfunction_sep,46"
category=category_1196
mapfunction=yes
show=both

[mapelement_603]
sprite="mapfunction_sep,47"
category=category_1197
mapfunction=yes
show=both

[mapelement_604]
sprite="mapfunction_sep,48"
category=category_1198
mapfunction=yes
show=both

[mapelement_605]
sprite="mapfunction_sep,49"
category=category_1199
mapfunction=yes
show=both

[mapelement_606]
sprite="mapfunction_sep,50"
category=category_1200
mapfunction=yes
show=both

[mapelement_607]
sprite="mapfunction_sep,51"
category=category_1201
mapfunction=yes
show=both

[mapelement_608]
sprite="mapfunction_sep,52"
category=category_1202
mapfunction=yes
show=both

[mapelement_609]
sprite="mapfunction_sep,54"
category=category_1203
mapfunction=yes
show=both

[mapelement_610]
sprite="mapfunction_sep,55"
category=category_1204
mapfunction=yes
show=both

[mapelement_611]
sprite="mapfunction_sep,53"
category=category_1205
mapfunction=yes
show=both

[mapelement_612]
sprite="mapfunction_sep,56"
category=category_1206
mapfunction=yes
show=both

[mapelement_613]
sprite="mapfunction_sep,58"
category=category_1207
mapfunction=yes
show=both

[mapelement_614]
sprite="mapfunction_sep,59"
category=category_1208
mapfunction=yes
show=both

[mapelement_615]
sprite="mapfunction_sep,60"
category=category_1209
mapfunction=yes
show=both

[mapelement_616]
sprite="mapfunction_sep,61"
category=category_1210
mapfunction=yes
show=both

[mapelement_617]
sprite="mapfunction_sep,62"
mapfunction=yes
show=both

[mapelement_618]
sprite="mapfunction_sep,63"
category=category_1211
mapfunction=yes
show=both

[mapelement_619]
sprite="mapfunction_sep,65"
category=category_1212
mapfunction=yes
show=both

[mapelement_620]
sprite="mapfunction_sep,55"
category=category_1213
mapfunction=yes
show=both

[mapelement_621]
sprite="mapfunction_sep,57"
category=category_1214
mapfunction=yes
show=both

[mapelement_622]
sprite="mapfunction_sep,67"
category=category_1215
mapfunction=yes
show=both

[mapelement_623]
sprite="mapfunction_sep,68"
category=category_1216
mapfunction=yes
show=both

[mapelement_624]
sprite="mapfunction_sep,69"
mapfunction=yes
show=both

[mapelement_625]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_626]
sprite="mapfunction_sep,71"
category=category_1218
mapfunction=yes
show=both

[mapelement_627]
sprite="mapfunction_sep,72"
category=category_1219
mapfunction=yes
show=both

[mapelement_628]
sprite="mapfunction_sep,73"
category=category_1220
mapfunction=yes
show=both

[mapelement_629]
sprite="mapfunction_sep,74"
category=category_1221
mapfunction=yes
show=both

[mapelement_630]
sprite="mapfunction_sep,75"
category=category_1260
mapfunction=yes
show=both

[mapelement_631]
sprite="mapfunction_sep,76"
category=category_1222
mapfunction=yes
show=both

[mapelement_632]
sprite="mapfunction_sep,93"
category=category_1223
mapfunction=yes
show=both

[mapelement_633]
sprite="mapfunction_sep,77"
category=category_1224
mapfunction=yes
show=both

[mapelement_634]
sprite="mapfunction_sep,92"
category=category_1225
mapfunction=yes
show=both

[mapelement_635]
sprite="mapfunction_sep,94"
category=category_1226
mapfunction=yes
show=both

[mapelement_636]
sprite="mapfunction_sep,95"
category=category_1227
mapfunction=yes
show=both

[mapelement_637]
sprite="mapfunction_sep,78"
category=category_1228
mapfunction=yes
show=both

[mapelement_638]
sprite="mapfunction_sep,79"
mapfunction=yes
show=both

[mapelement_639]
sprite="mapfunction_sep,80"
mapfunction=yes
show=both

[mapelement_640]
sprite="mapfunction_sep,81"
mapfunction=yes
show=both

[mapelement_641]
sprite="mapfunction_sep,82"
mapfunction=yes
show=both

[mapelement_642]
sprite="mapfunction_sep,83"
mapfunction=yes
show=both

[mapelement_643]
sprite="mapfunction_sep,84"
mapfunction=yes
show=both

[mapelement_644]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_180,0,7

[mapelement_645]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_180,7,9999

[mapelement_646]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1850,0,5

[mapelement_647]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1850,5,9999

[mapelement_648]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_961,0,60

[mapelement_649]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_961,60,9999

[mapelement_650]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5331,0,35

[mapelement_651]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5331,35,9999

[mapelement_652]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5032,0,63

[mapelement_653]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5032,63,9999

[mapelement_654]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_148,0,11

[mapelement_655]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_148,11,9999

[mapelement_656]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3523,0,150

[mapelement_657]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3523,150,9999

[mapelement_658]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5733,0,60

[mapelement_659]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5733,60,9999

[mapelement_660]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_147,0,6

[mapelement_661]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_147,6,9999

[mapelement_662]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1404,0,127

[mapelement_663]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1404,127,9999

[mapelement_664]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5133,0,90

[mapelement_665]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5133,90,9999

[mapelement_666]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2326,0,90

[mapelement_667]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2326,90,9999

[mapelement_668]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1803,0,90

[mapelement_669]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1803,90,9999

[mapelement_670]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3550,0,11

[mapelement_671]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3550,11,9999

[mapelement_672]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_4105,0,18

[mapelement_673]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_4105,18,9999

[mapelement_674]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_451,0,2

[mapelement_675]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_451,2,9999

[mapelement_676]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1372,0,125

[mapelement_677]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1372,125,9999

[mapelement_678]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_532,0,11

[mapelement_679]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_532,11,9999

[mapelement_680]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2258,0,13

[mapelement_681]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2258,13,9999

[mapelement_682]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1938,0,110

[mapelement_683]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1938,110,9999

[mapelement_684]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_4684,0,150

[mapelement_685]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_4684,150,9999

[mapelement_686]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1051,0,10

[mapelement_687]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1051,10,9999

[mapelement_688]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3185,0,240

[mapelement_689]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3185,240,9999

[mapelement_690]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_334,0,28

[mapelement_691]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_334,28,9999

[mapelement_692]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_657,0,2

[mapelement_693]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_657,2,9999

[mapelement_694]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2610,0,14

[mapelement_695]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2610,14,9999

[mapelement_696]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5387,0,250

[mapelement_697]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5387,250,9999

[mapelement_698]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_302,0,61

[mapelement_699]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_302,60,9999

[mapelement_700]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both

[mapelement_701]
text=Kalphite<br>Hive
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_702]
text=Mobilising<br>Armies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_703]
sprite="mapfunction_sep,99"
mapfunction=yes
show=both

[mapelement_704]
sprite="mapfunction_sep,100"
mapfunction=yes
show=both

[mapelement_705]
sprite="mapfunction_sep,101"
mapfunction=yes
show=both

[mapelement_706]
sprite="mapfunction_sep,102"
mapfunction=yes
show=both

[mapelement_707]
sprite="mapfunction_sep,103"
category=category_1270
mapfunction=yes
show=both

[mapelement_708]
text=Aquanites
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_709]
sprite="mapdots_interface,1"
mapfunction=no
show=minimap

[mapelement_710]
text=Rogues'<br>Den
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

