// 0
[mapelement_0]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1
[mapelement_1]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 2
[mapelement_2]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 3
[mapelement_3]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 4
[mapelement_4]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 5
[mapelement_5]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 6
[mapelement_6]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 7
[mapelement_7]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 8
[mapelement_8]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 9
[mapelement_9]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 10
[mapelement_10]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 11
[mapelement_11]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 12
[mapelement_12]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 13
[mapelement_13]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 14
[mapelement_14]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 15
[mapelement_15]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 16
[mapelement_16]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 17
[mapelement_17]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 18
[mapelement_18]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 19
[mapelement_19]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 20
[mapelement_20]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 21
[mapelement_21]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 22
[mapelement_22]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 23
[mapelement_23]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 24
[mapelement_24]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 25
[mapelement_25]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 26
[mapelement_26]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 27
[mapelement_27]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 28
[mapelement_28]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 29
[mapelement_29]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 30
[mapelement_30]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 31
[mapelement_31]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 32
[mapelement_32]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 33
[mapelement_33]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 34
[mapelement_34]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 35
[mapelement_35]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 36
[mapelement_36]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 37
[mapelement_37]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 38
[mapelement_38]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 39
[mapelement_39]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 40
[mapelement_40]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 41
[mapelement_41]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 42
[mapelement_42]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 43
[mapelement_43]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 44
[mapelement_44]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 45
[mapelement_45]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 46
[mapelement_46]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 47
[mapelement_47]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 48
[mapelement_48]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 49
[mapelement_49]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 50
[mapelement_50]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 51
[mapelement_51]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 52
[mapelement_52]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 53
[mapelement_53]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 54
[mapelement_54]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 55
[mapelement_55]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 56
[mapelement_56]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 57
[mapelement_57]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 58
[mapelement_58]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 59
[mapelement_59]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 60
[mapelement_60]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 61
[mapelement_61]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 62
[mapelement_62]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 63
[mapelement_63]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 64
[mapelement_64]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 65
[mapelement_65]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 66
[mapelement_66]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 67
[mapelement_67]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 68
[mapelement_68]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 69
[mapelement_69]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 70
[mapelement_70]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 71
[mapelement_71]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 72
[mapelement_72]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 73
[mapelement_73]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 74
[mapelement_74]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 75
[mapelement_75]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 76
[mapelement_76]
text=Exit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

// 77
[mapelement_77]
text=East Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

// 78
[mapelement_78]
text=West Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

// 79
[mapelement_79]
text=Soul Obelisk
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

// 80
[mapelement_80]
text=Entrance
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 81
[mapelement_81]
text=Exit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 82
[mapelement_82]
text=Lumbridge
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 83
[mapelement_83]
text=Varrock
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 84
[mapelement_84]
text=Kingdom of<br>Misthalin
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 85
[mapelement_85]
text=Al Kharid
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 86
[mapelement_86]
text=Duel<br>Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 87
[mapelement_87]
text=Shantay<br>Pass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 88
[mapelement_88]
text=Toll<br>Gate
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 89
[mapelement_89]
text=Tutorial Island
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 90
[mapelement_90]
text=Port<br>Sarim
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 91
[mapelement_91]
text=Falador
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 92
[mapelement_92]
text=Edgeville
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 93
[mapelement_93]
text=Brimhaven
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 94
[mapelement_94]
text=Karamja
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 95
[mapelement_95]
text=Crandor
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 96
[mapelement_96]
text=Entrana
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 97
[mapelement_97]
text=Draynor<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 98
[mapelement_98]
text=Jail
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 99
[mapelement_99]
text=Market
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 100
[mapelement_100]
text=Draynor Manor
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 101
[mapelement_101]
text=Barbarian<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950
condition=varplayerbit_5819,0,0

// 102
[mapelement_102]
text=Desert Mining<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 103
[mapelement_103]
text=Bedabin<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 104
[mapelement_104]
text=Exam Centre
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 105
[mapelement_105]
text=Digsite
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 106
[mapelement_106]
text=Lumber Yard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 107
[mapelement_107]
text=Palace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 108
[mapelement_108]
text=Cooks'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 109
[mapelement_109]
text=Monastery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 110
[mapelement_110]
text=Dwarven<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 111
[mapelement_111]
text=Ice<br>Mountain
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 112
[mapelement_112]
text=Black Knights'<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 113
[mapelement_113]
text=Goblin<br>Village
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 114
[mapelement_114]
text=White Knights'<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 115
[mapelement_115]
text=Park
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 116
[mapelement_116]
text=Kingdom of<br>Asgarnia
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 117
[mapelement_117]
text=Dark Wizards'<br>Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 118
[mapelement_118]
text=Slayer<br>Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 119
[mapelement_119]
text=Melzar's<br>Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 120
[mapelement_120]
text=Rimmington
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 121
[mapelement_121]
text=Wizards' Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 122
[mapelement_122]
text=Lumbridge<br>Swamp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 123
[mapelement_123]
text=Fishing<br>Platform
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 124
[mapelement_124]
text=Tai Bwo Wannai
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 125
[mapelement_125]
text=Shilo Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 126
[mapelement_126]
text=Shipyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 127
[mapelement_127]
text=Cairn Isle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 128
[mapelement_128]
text=Kharazi Jungle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 129
[mapelement_129]
text=Chaos<br>Temple
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 130
[mapelement_130]
text=Graveyard of<br>Shadows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 131
[mapelement_131]
text=Bandit<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 132
[mapelement_132]
text=Dark Warriors'<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 133
[mapelement_133]
text=Ruins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 134
[mapelement_134]
text=The Forgotten<br>Cemetery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 135
[mapelement_135]
text=Red Dragon<br>Isle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 136
[mapelement_136]
text=Wilderness
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 137
[mapelement_137]
text=Lava Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 138
[mapelement_138]
text=Frozen Waste<br>Plateau
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 139
[mapelement_139]
text=Agility Training<br>Area
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 140
[mapelement_140]
text=Pirates'<br>Hideout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 141
[mapelement_141]
text=Mage Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 142
[mapelement_142]
text=Deserted<br>Keep
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 143
[mapelement_143]
text=Scorpion<br>Pit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 144
[mapelement_144]
text=Rogues' Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 145
[mapelement_145]
text=Demonic<br>Ruins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 146
[mapelement_146]
text=Heroes'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 147
[mapelement_147]
text=Druids'<br>Circle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 148
[mapelement_148]
text=Taverley
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 149
[mapelement_149]
text=White Wolf<br>Mountain
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 150
[mapelement_150]
text=Catherby
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 151
[mapelement_151]
text=Camelot<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 152
[mapelement_152]
text=Seers'<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 153
[mapelement_153]
text=Sinclair Mansion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 154
[mapelement_154]
text=Flax
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 155
[mapelement_155]
text=Beehives
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 156
[mapelement_156]
text=Sorcerer's Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 157
[mapelement_157]
text=Keep<br>Le Faye
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 158
[mapelement_158]
text=Legends'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 159
[mapelement_159]
text=Hemenster
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 160
[mapelement_160]
text=McGrubor's<br>Wood
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 161
[mapelement_161]
text=Coal<br>Trucks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 162
[mapelement_162]
text=Fishing<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 163
[mapelement_163]
text=Kingdom of<br>Kandarin
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 164
[mapelement_164]
text=East<br>Ardougne
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 165
[mapelement_165]
text=West<br>Ardougne
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 166
[mapelement_166]
text=Ardougne<br>Sewers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 167
[mapelement_167]
text=Combat<br>Training<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 168
[mapelement_168]
text=Tree Gnome<br>Stronghold
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 169
[mapelement_169]
text=Grand Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 170
[mapelement_170]
text=Swamp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 171
[mapelement_171]
text=Gnome Ball<br>Field
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 172
[mapelement_172]
text=Barbarian<br>Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 173
[mapelement_173]
text=Underground<br>Pass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 174
[mapelement_174]
text=Battlefield
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 175
[mapelement_175]
text=Baxtorian<br>Falls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 176
[mapelement_176]
text=Tree Gnome<br>Village
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 177
[mapelement_177]
text=Fight<br>Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 178
[mapelement_178]
text=Port<br>Khazard
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 179
[mapelement_179]
text=Yanille
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 180
[mapelement_180]
text=Wizards'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 181
[mapelement_181]
text=Observatory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 182
[mapelement_182]
text=Necromancer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 183
[mapelement_183]
text=Gu'Tanoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 184
[mapelement_184]
text=Feldip<br>Hills
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 185
[mapelement_185]
text=Ardougne<br>Zoo
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 186
[mapelement_186]
text=Morytania
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 187
[mapelement_187]
text=Mort Myre<br>Swamp
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 188
[mapelement_188]
text=Canifis
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 189
[mapelement_189]
text=River<br>Salve
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 190
[mapelement_190]
text=River Lum
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 191
[mapelement_191]
text=Temple
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 192
[mapelement_192]
text=Agility<br>Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 193
[mapelement_193]
text=Burthorpe
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 194
[mapelement_194]
text=Death<br>Plateau
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 195
[mapelement_195]
text=Tirannwn
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 196
[mapelement_196]
text=Isafdar
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 197
[mapelement_197]
text=Arandar
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 198
[mapelement_198]
text=Prifddinas
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 199
[mapelement_199]
text=Tyras<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 200
[mapelement_200]
text=Elf<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 201
[mapelement_201]
text=Trollheim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 202
[mapelement_202]
text=Troll<br>Stronghold
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 203
[mapelement_203]
text=Mort'ton
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 204
[mapelement_204]
text=The<br>Hollows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 205
[mapelement_205]
text=Poison Waste
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 206
[mapelement_206]
text=Castle Wars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 207
[mapelement_207]
text=Champions'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 208
[mapelement_208]
text=Rellekka
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 209
[mapelement_209]
text=Golden<br>Apple Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 210
[mapelement_210]
text=Lighthouse
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 211
[mapelement_211]
text=Fremennik<br>Province
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 212
[mapelement_212]
text=Crafting<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 213
[mapelement_213]
text=Haunted<br>Woods
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 214
[mapelement_214]
text=Miscellania
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 215
[mapelement_215]
text=Etceteria
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 216
[mapelement_216]
text=Ape Atoll
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 217
[mapelement_217]
text=Crash<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 218
[mapelement_218]
text=Marim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 219
[mapelement_219]
text=Fenkenstrain's<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 220
[mapelement_220]
text=Mausoleum
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 221
[mapelement_221]
text=Trollweiss<br>Mountain
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 222
[mapelement_222]
text=Abandoned<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 223
[mapelement_223]
text=Ruins of<br>Uzer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 224
[mapelement_224]
text=River<br>Elid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 225
[mapelement_225]
sprite="mapfunction_sep,96"
category=category_1240
mapfunction=yes
show=both

// 226
[mapelement_226]
text=Pollnivneach
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 227
[mapelement_227]
text=Pyramid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 228
[mapelement_228]
text=Menaphos
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 229
[mapelement_229]
text=Sophanem
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 230
[mapelement_230]
text=Agility<br>Pyramid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 231
[mapelement_231]
text=Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 232
[mapelement_232]
text=Port<br>Phasmatys
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 233
[mapelement_233]
text=Ectofuntus
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 234
[mapelement_234]
text=Mountain<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 235
[mapelement_235]
text=Kharidian<br>Desert
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 236
[mapelement_236]
text=Ice Path
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 237
[mapelement_237]
text=Barrows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 238
[mapelement_238]
text=Jiggig
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 239
[mapelement_239]
text=Mudskipper<br>Point
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 240
[mapelement_240]
text=Nardah
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 241
[mapelement_241]
text=Mage<br>Training<br>Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 242
[mapelement_242]
text=Keldagrim<br>Entrance
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 243
[mapelement_243]
text=Waterbirth<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 244
[mapelement_244]
text=Lletya
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 245
[mapelement_245]
text=Burgh de Rott
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 246
[mapelement_246]
text=Lizards
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 247
[mapelement_247]
text=Quarry
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 248
[mapelement_248]
text=Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 249
[mapelement_249]
text=Mos Le'Harmless
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 250
[mapelement_250]
text=Distilleries
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 251
[mapelement_251]
text=Ranging<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 252
[mapelement_252]
text=Dragontooth<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 253
[mapelement_253]
text=Piscatoris<br>Fishing<br>Colony
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 254
[mapelement_254]
text=Here Be<br>Penguins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 255
[mapelement_255]
text=Void Knights'<br>Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 256
[mapelement_256]
text=Lunar Isle
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 257
[mapelement_257]
text=Pirates' Cove
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 258
[mapelement_258]
text=Vultures
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 259
[mapelement_259]
text=Port<br>Tyras
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 260
[mapelement_260]
text=Castle<br>Drakan
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 261
[mapelement_261]
text=Sanguinesti<br>Region
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 262
[mapelement_262]
text=Meiyerditch
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 263
[mapelement_263]
text=Witchaven
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 264
[mapelement_264]
text=Warriors'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 265
[mapelement_265]
text=Musa Point
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 266
[mapelement_266]
text=Eagles'<br>Peak
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 267
[mapelement_267]
text=Falconer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 268
[mapelement_268]
text=Barbarian<br>Assault
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 269
[mapelement_269]
text=Iceberg
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 270
[mapelement_270]
text=Pest<br>Control
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 271
[mapelement_271]
text=Neitiznot
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 272
[mapelement_272]
text=Jatizso
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 273
[mapelement_273]
text=Fremennik Isles
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

// 274
[mapelement_274]
text=Tower of<br>Life
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 275
[mapelement_275]
text=Clocktower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 276
[mapelement_276]
text=Harmony
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 277
[mapelement_277]
text=Trawler
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 278
[mapelement_278]
text=Otto's<br>Grotto
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 279
[mapelement_279]
text=Party Room
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 280
[mapelement_280]
text=Courthouse
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 281
[mapelement_281]
text=God Wars<br>Dungeon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 282
[mapelement_282]
text=Wilderness<br>Volcano
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 283
[mapelement_283]
text=Clan<br>Wars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 284
[mapelement_284]
text=Grand Exchange
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 285
[mapelement_285]
text=Oo'glog
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 286
[mapelement_286]
text=Fist of<br>Guthix
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 287
[mapelement_287]
text=Stealing<br>Creation
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 288
[mapelement_288]
text=Soul Wars
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 289
[mapelement_289]
text=Queen's<br>Chamber
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 290
[mapelement_290]
text=Soldiers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 291
[mapelement_291]
text=Guardians
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 292
[mapelement_292]
text=Ice Queen's<br>Lair
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 293
[mapelement_293]
text=Fountain<br>of Heroes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 294
[mapelement_294]
text=Mountain<br>dwarves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 295
[mapelement_295]
text=Nora T. Hagg's<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 296
[mapelement_296]
text=Salarin the<br>Twisted
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 297
[mapelement_297]
text=H.A.M. Cult
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 298
[mapelement_298]
text=Draynor Sewers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 299
[mapelement_299]
text=Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 300
[mapelement_300]
text=Watermill<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 301
[mapelement_301]
text=Champions'<br>Challenge
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 302
[mapelement_302]
text=Draynor Manor<br>basement
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 303
[mapelement_303]
text=VTAM Corporation
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 304
[mapelement_304]
text=Bank vault
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 305
[mapelement_305]
text=Goblin Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 306
[mapelement_306]
text=Chasm of<br>Tears
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 307
[mapelement_307]
text=Tears of<br>Guthix
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 308
[mapelement_308]
text=Lumbridge<br>Castle<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 309
[mapelement_309]
text=Giant frogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 310
[mapelement_310]
text=Hill giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 311
[mapelement_311]
text=Chronozon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 312
[mapelement_312]
text=Here be<br>dead stuff
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 313
[mapelement_313]
text=Thugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 314
[mapelement_314]
text=Dave's<br>Basement<br>of Doom
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 315
[mapelement_315]
text=Poison spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 316
[mapelement_316]
text=Poison<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 317
[mapelement_317]
text=Zombies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 318
[mapelement_318]
text=Zombies & rocks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 319
[mapelement_319]
text=Skeletons<br>& zombies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 320
[mapelement_320]
text=Earth warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 321
[mapelement_321]
text=Earth<br>warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 322
[mapelement_322]
text=Skeletons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 323
[mapelement_323]
text=Black demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 324
[mapelement_324]
text=Black<br>demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 325
[mapelement_325]
text=Chaos<br>druids
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 326
[mapelement_326]
text=Hobgoblins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 327
[mapelement_327]
text=Red spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 328
[mapelement_328]
text=Red<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 329
[mapelement_329]
text=Rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 330
[mapelement_330]
text=Banshees
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 331
[mapelement_331]
text=Kurask
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 332
[mapelement_332]
text=Cave crawlers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 333
[mapelement_333]
text=Turoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 334
[mapelement_334]
text=Basilisks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 335
[mapelement_335]
text=Aberrant<br>spectres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 336
[mapelement_336]
text=Rock<br>slugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 337
[mapelement_337]
text=Cockatrice
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 338
[mapelement_338]
text=Pyrefiends
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 339
[mapelement_339]
text=Jellies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 340
[mapelement_340]
text=Throne room
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 341
[mapelement_341]
text=Beware of the<br>mushrooms
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 342
[mapelement_342]
text=Shrine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 343
[mapelement_343]
text=Otherworldly<br>beings
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 344
[mapelement_344]
text=Puro-puro
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 345
[mapelement_345]
text=Moss giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 346
[mapelement_346]
text=Moss<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 347
[mapelement_347]
text=Dogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 348
[mapelement_348]
text=Fire<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 349
[mapelement_349]
text=Red dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 350
[mapelement_350]
text=Bronze<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 351
[mapelement_351]
text=Iron & steel<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 352
[mapelement_352]
text=Greater demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 353
[mapelement_353]
text=Agility Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 354
[mapelement_354]
text=Jogres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 355
[mapelement_355]
text=Elvarg
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 356
[mapelement_356]
text=Lesser demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 357
[mapelement_357]
text=Gift of<br>Peace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 358
[mapelement_358]
text=Grain of<br>Plenty
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 359
[mapelement_359]
text=Box of<br>Health
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 360
[mapelement_360]
text=Cradle of<br>Life
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 361
[mapelement_361]
text=Crypt<br>rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 362
[mapelement_362]
text=Dungeon<br>rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 363
[mapelement_363]
text=Nechryael
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 364
[mapelement_364]
text=Dagannoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 365
[mapelement_365]
text=Infernal<br>magi
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 366
[mapelement_366]
text=Dragons & fire<br>elementals
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 367
[mapelement_367]
text=Dust<br>devils
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 368
[mapelement_368]
text=Waterfiends
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 369
[mapelement_369]
text=Rock<br>crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 370
[mapelement_370]
text=Ice<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 371
[mapelement_371]
text=Zamorak<br>fighters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 372
[mapelement_372]
text=Cave<br>bugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 373
[mapelement_373]
text=Shadow<br>hounds &<br>wolves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 374
[mapelement_374]
text=Dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 375
[mapelement_375]
text=Giant<br>ants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 376
[mapelement_376]
text=Spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 377
[mapelement_377]
text=Shadow<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 378
[mapelement_378]
text=Crypt & shadow<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 379
[mapelement_379]
text=Leeches
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 380
[mapelement_380]
text=Ice warriors<br>& giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 381
[mapelement_381]
text=Gargoyles
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 382
[mapelement_382]
text=Trolls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 383
[mapelement_383]
text=Ice trolls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 384
[mapelement_384]
text=Monks of<br>Zamorak
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 385
[mapelement_385]
text=Mummies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 386
[mapelement_386]
text=Zombies,<br>skeletons &<br>animated<br>items
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 387
[mapelement_387]
text=Fight Pit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 388
[mapelement_388]
text=Fight Cave
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 389
[mapelement_389]
text=Library
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 390
[mapelement_390]
text=Terror dogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 391
[mapelement_391]
text=Anger
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 392
[mapelement_392]
text=Hopelessness
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 393
[mapelement_393]
text=Confusion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 394
[mapelement_394]
text=Fear
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 395
[mapelement_395]
text=Saradomin's<br>Encampment
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 396
[mapelement_396]
text=Zamorak's<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 397
[mapelement_397]
text=Armadyl's<br>Eyrie
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 398
[mapelement_398]
text=Bandos's<br>Stronghold
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 399
[mapelement_399]
text=Distillery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 400
[mapelement_400]
text=Dead people
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 401
[mapelement_401]
text=Nothing<br>interesting<br>happens<br>here
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 402
[mapelement_402]
text=Beware of<br>the scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 403
[mapelement_403]
text=Mining Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 404
[mapelement_404]
text=Access to<br>Falador
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 405
[mapelement_405]
text=Hammerspike's<br>hangout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 406
[mapelement_406]
text=Pickaxe<br>factory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 407
[mapelement_407]
text=Boot
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 408
[mapelement_408]
text=River Kelda
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 409
[mapelement_409]
text=Dondakan's<br>rock
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 410
[mapelement_410]
text=Minecarts
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 411
[mapelement_411]
text=Blast<br>Furnace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 412
[mapelement_412]
text=Brewery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 413
[mapelement_413]
text=Agility course
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 414
[mapelement_414]
text=Wire<br>machine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 415
[mapelement_415]
text=Bone<br>collector
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 416
[mapelement_416]
text=Oldak's<br>teleportation<br>laboratory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 417
[mapelement_417]
text=Station
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 418
[mapelement_418]
text=Council<br>chamber
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 419
[mapelement_419]
text=Ur-tag
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 420
[mapelement_420]
text=Ur-meg
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 421
[mapelement_421]
text=Ur-zek & Ur-taal
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 422
[mapelement_422]
text=Tegdak
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 423
[mapelement_423]
text=Ur-vass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 424
[mapelement_424]
text=Nursery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 425
[mapelement_425]
text=Cauldron of<br>Thunder
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 426
[mapelement_426]
text=Black Knights'<br>Base
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 427
[mapelement_427]
text=Hellhounds
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 428
[mapelement_428]
text=Fire Obelisk
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 429
[mapelement_429]
text=Black dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 430
[mapelement_430]
text=Black<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 431
[mapelement_431]
text=Dramen Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 432
[mapelement_432]
text=Animated<br>axes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 433
[mapelement_433]
text=Chaos<br>dwarves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 434
[mapelement_434]
text=Blue<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 435
[mapelement_435]
text=Poisonous<br>scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 436
[mapelement_436]
text=Agility<br>course<br>spikes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 437
[mapelement_437]
text=Mage Arena<br>bank
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 438
[mapelement_438]
text=King<br>Black<br>Dragon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 439
[mapelement_439]
text=Shadow<br>warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 440
[mapelement_440]
text=Pit scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 441
[mapelement_441]
text=Rat Pits
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 442
[mapelement_442]
text=Bats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 443
[mapelement_443]
text=Ogres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 444
[mapelement_444]
text=Here be<br>goblins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 445
[mapelement_445]
text=Skeletal wyverns
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 446
[mapelement_446]
text=Pirates
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 447
[mapelement_447]
text=Muggers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 448
[mapelement_448]
text=Black<br>Guard<br>H.Q.
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 449
[mapelement_449]
text=Zanik's<br>bedroom
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 450
[mapelement_450]
text=Essence<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 451
[mapelement_451]
text=Miscellania<br>Expansion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 452
[mapelement_452]
text=Sea snakes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 453
[mapelement_453]
text=Altar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 454
[mapelement_454]
text=Lizards &<br>Zamorak fighters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 455
[mapelement_455]
text=Goutweed<br>store
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 456
[mapelement_456]
text=Troll<br>generals
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 457
[mapelement_457]
text=Kitchen
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 458
[mapelement_458]
text=Tanglefeet
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 459
[mapelement_459]
text=Giant rock crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 460
[mapelement_460]
text=Giant<br>rock crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 461
[mapelement_461]
text=Rock lobsters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 462
[mapelement_462]
text=Rock<br>lobsters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 463
[mapelement_463]
text=Wallasalki
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 464
[mapelement_464]
text=Dagannoth<br>Kings
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 465
[mapelement_465]
text=Volcano
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 466
[mapelement_466]
text=Cave horrors<br>&<br>albino bats
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 467
[mapelement_467]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 468
[mapelement_468]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 469
[mapelement_469]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 470
[mapelement_470]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 471
[mapelement_471]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 472
[mapelement_472]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 473
[mapelement_473]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 474
[mapelement_474]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 475
[mapelement_475]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 476
[mapelement_476]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 477
[mapelement_477]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 478
[mapelement_478]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 479
[mapelement_479]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 480
[mapelement_480]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 481
[mapelement_481]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 482
[mapelement_482]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 483
[mapelement_483]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 484
[mapelement_484]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 485
[mapelement_485]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 486
[mapelement_486]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 487
[mapelement_487]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 488
[mapelement_488]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 489
[mapelement_489]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 490
[mapelement_490]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 491
[mapelement_491]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 492
[mapelement_492]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 493
[mapelement_493]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 494
[mapelement_494]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 495
[mapelement_495]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 496
[mapelement_496]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 497
[mapelement_497]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 498
[mapelement_498]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 499
[mapelement_499]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 500
[mapelement_500]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 501
[mapelement_501]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 502
[mapelement_502]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 503
[mapelement_503]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 504
[mapelement_504]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 505
[mapelement_505]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 506
[mapelement_506]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 507
[mapelement_507]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 508
[mapelement_508]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 509
[mapelement_509]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 510
[mapelement_510]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 511
[mapelement_511]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 512
[mapelement_512]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 513
[mapelement_513]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 514
[mapelement_514]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 515
[mapelement_515]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 516
[mapelement_516]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 517
[mapelement_517]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 518
[mapelement_518]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 519
[mapelement_519]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 520
[mapelement_520]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 521
[mapelement_521]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 522
[mapelement_522]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 523
[mapelement_523]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 524
[mapelement_524]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 525
[mapelement_525]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 526
[mapelement_526]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 527
[mapelement_527]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 528
[mapelement_528]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 529
[mapelement_529]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 530
[mapelement_530]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 531
[mapelement_531]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 532
[mapelement_532]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 533
[mapelement_533]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 534
[mapelement_534]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 535
[mapelement_535]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 536
[mapelement_536]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 537
[mapelement_537]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 538
[mapelement_538]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 539
[mapelement_539]
show=both
condition=varplayerbit_6913,12,12
condition2=varplayerbit_5332,0,12
polygonpoint0=0,0
polygonpoint1=0,64
polygonpoint2=64,64
polygonpoint3=64,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 540
[mapelement_540]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 541
[mapelement_541]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 542
[mapelement_542]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 543
[mapelement_543]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 544
[mapelement_544]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 545
[mapelement_545]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 546
[mapelement_546]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 547
[mapelement_547]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 548
[mapelement_548]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 549
[mapelement_549]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 550
[mapelement_550]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 551
[mapelement_551]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 552
[mapelement_552]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 553
[mapelement_553]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 554
[mapelement_554]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 555
[mapelement_555]
sprite="mapfunction_sep,0"
category=category_951
mapfunction=yes
show=both

// 556
[mapelement_556]
sprite="mapfunction_sep,1"
category=category_952
mapfunction=yes
show=both

// 557
[mapelement_557]
sprite="mapfunction_sep,2"
category=category_953
mapfunction=yes
show=both

// 558
[mapelement_558]
sprite="mapfunction_sep,3"
category=category_954
mapfunction=yes
show=both

// 559
[mapelement_559]
sprite="mapfunction_sep,4"
category=category_955
mapfunction=yes
show=both

// 560
[mapelement_560]
sprite="mapfunction_sep,5"
category=category_1156
mapfunction=yes
show=both

// 561
[mapelement_561]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both

// 562
[mapelement_562]
sprite="mapfunction_sep,7"
category=category_1158
mapfunction=yes
show=both

// 563
[mapelement_563]
sprite="mapfunction_sep,8"
category=category_1159
mapfunction=yes
show=both

// 564
[mapelement_564]
sprite="mapfunction_sep,9"
category=category_1160
mapfunction=yes
show=both

// 565
[mapelement_565]
sprite="mapfunction_sep,10"
category=category_1161
mapfunction=yes
show=both

// 566
[mapelement_566]
sprite="mapfunction_sep,11"
category=category_1162
mapfunction=yes
show=both

// 567
[mapelement_567]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=both

// 568
[mapelement_568]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=minimap

// 569
[mapelement_569]
sprite="mapfunction_sep,13"
category=category_1163
mapfunction=yes
show=both

// 570
[mapelement_570]
sprite="mapfunction_sep,14"
category=category_1164
mapfunction=yes
show=both

// 571
[mapelement_571]
sprite="mapfunction_sep,15"
category=category_1165
mapfunction=yes
show=both

// 572
[mapelement_572]
sprite="mapfunction_sep,16"
category=category_1166
mapfunction=yes
show=both

// 573
[mapelement_573]
sprite="mapfunction_sep,17"
category=category_1167
mapfunction=yes
show=both

// 574
[mapelement_574]
sprite="mapfunction_sep,18"
category=category_1168
mapfunction=yes
show=both

// 575
[mapelement_575]
sprite="mapfunction_sep,19"
category=category_1169
mapfunction=yes
show=both

// 576
[mapelement_576]
sprite="mapfunction_sep,20"
category=category_1170
mapfunction=yes
show=both

// 577
[mapelement_577]
sprite="mapfunction_sep,21"
category=category_1171
mapfunction=yes
show=both

// 578
[mapelement_578]
sprite="mapfunction_sep,22"
category=category_1172
mapfunction=yes
show=both

// 579
[mapelement_579]
sprite="mapfunction_sep,23"
category=category_1173
mapfunction=yes
show=both

// 580
[mapelement_580]
sprite="mapfunction_sep,24"
category=category_1174
mapfunction=yes
show=both

// 581
[mapelement_581]
sprite="mapfunction_sep,25"
category=category_1175
mapfunction=yes
show=both

// 582
[mapelement_582]
sprite="mapfunction_sep,26"
category=category_1176
mapfunction=yes
show=both

// 583
[mapelement_583]
sprite="mapfunction_sep,27"
category=category_1177
mapfunction=yes
show=both

// 584
[mapelement_584]
sprite="mapfunction_sep,28"
category=category_1178
mapfunction=yes
show=both

// 585
[mapelement_585]
sprite="mapfunction_sep,29"
category=category_1179
mapfunction=yes
show=both

// 586
[mapelement_586]
sprite="mapfunction_sep,30"
category=category_1180
mapfunction=yes
show=both

// 587
[mapelement_587]
sprite="mapfunction_sep,31"
category=category_1181
mapfunction=yes
show=both

// 588
[mapelement_588]
sprite="mapfunction_sep,32"
category=category_1182
mapfunction=yes
show=both

// 589
[mapelement_589]
sprite="mapfunction_sep,33"
category=category_1183
mapfunction=yes
show=both

// 590
[mapelement_590]
sprite="mapfunction_sep,34"
category=category_1184
mapfunction=yes
show=both

// 591
[mapelement_591]
sprite="mapfunction_sep,35"
category=category_1185
mapfunction=yes
show=both

// 592
[mapelement_592]
sprite="mapfunction_sep,36"
category=category_1186
mapfunction=yes
show=both

// 593
[mapelement_593]
sprite="mapfunction_sep,37"
category=category_1187
mapfunction=yes
show=both

// 594
[mapelement_594]
sprite="mapfunction_sep,38"
category=category_1188
mapfunction=yes
show=both

// 595
[mapelement_595]
sprite="mapfunction_sep,39"
category=category_1189
mapfunction=yes
show=both

// 596
[mapelement_596]
sprite="mapfunction_sep,40"
category=category_1190
mapfunction=yes
show=both

// 597
[mapelement_597]
sprite="mapfunction_sep,41"
category=category_1191
mapfunction=yes
show=both

// 598
[mapelement_598]
sprite="mapfunction_sep,42"
category=category_1192
mapfunction=yes
show=both

// 599
[mapelement_599]
sprite="mapfunction_sep,43"
category=category_1193
mapfunction=yes
show=both

// 600
[mapelement_600]
sprite="mapfunction_sep,44"
category=category_1194
mapfunction=yes
show=both

// 601
[mapelement_601]
sprite="mapfunction_sep,45"
category=category_1195
mapfunction=yes
show=both

// 602
[mapelement_602]
sprite="mapfunction_sep,46"
category=category_1196
mapfunction=yes
show=both

// 603
[mapelement_603]
sprite="mapfunction_sep,47"
category=category_1197
mapfunction=yes
show=both

// 604
[mapelement_604]
sprite="mapfunction_sep,48"
category=category_1198
mapfunction=yes
show=both

// 605
[mapelement_605]
sprite="mapfunction_sep,49"
category=category_1199
mapfunction=yes
show=both

// 606
[mapelement_606]
sprite="mapfunction_sep,50"
category=category_1200
mapfunction=yes
show=both

// 607
[mapelement_607]
sprite="mapfunction_sep,51"
category=category_1201
mapfunction=yes
show=both

// 608
[mapelement_608]
sprite="mapfunction_sep,52"
category=category_1202
mapfunction=yes
show=both

// 609
[mapelement_609]
sprite="mapfunction_sep,54"
category=category_1203
mapfunction=yes
show=both

// 610
[mapelement_610]
sprite="mapfunction_sep,55"
category=category_1204
mapfunction=yes
show=both

// 611
[mapelement_611]
sprite="mapfunction_sep,53"
category=category_1205
mapfunction=yes
show=both

// 612
[mapelement_612]
sprite="mapfunction_sep,56"
category=category_1206
mapfunction=yes
show=both

// 613
[mapelement_613]
sprite="mapfunction_sep,58"
category=category_1207
mapfunction=yes
show=both

// 614
[mapelement_614]
sprite="mapfunction_sep,59"
category=category_1208
mapfunction=yes
show=both

// 615
[mapelement_615]
sprite="mapfunction_sep,60"
category=category_1209
mapfunction=yes
show=both

// 616
[mapelement_616]
sprite="mapfunction_sep,61"
category=category_1210
mapfunction=yes
show=both

// 617
[mapelement_617]
sprite="mapfunction_sep,62"
mapfunction=yes
show=both

// 618
[mapelement_618]
sprite="mapfunction_sep,63"
category=category_1211
mapfunction=yes
show=both

// 619
[mapelement_619]
sprite="mapfunction_sep,65"
category=category_1212
mapfunction=yes
show=both

// 620
[mapelement_620]
sprite="mapfunction_sep,55"
category=category_1213
mapfunction=yes
show=both

// 621
[mapelement_621]
sprite="mapfunction_sep,57"
category=category_1214
mapfunction=yes
show=both

// 622
[mapelement_622]
sprite="mapfunction_sep,67"
category=category_1215
mapfunction=yes
show=both

// 623
[mapelement_623]
sprite="mapfunction_sep,68"
category=category_1216
mapfunction=yes
show=both

// 624
[mapelement_624]
sprite="mapfunction_sep,69"
mapfunction=yes
show=both

// 625
[mapelement_625]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 626
[mapelement_626]
sprite="mapfunction_sep,71"
category=category_1218
mapfunction=yes
show=both

// 627
[mapelement_627]
sprite="mapfunction_sep,72"
category=category_1219
mapfunction=yes
show=both

// 628
[mapelement_628]
sprite="mapfunction_sep,73"
category=category_1220
mapfunction=yes
show=both

// 629
[mapelement_629]
sprite="mapfunction_sep,74"
category=category_1221
mapfunction=yes
show=both

// 630
[mapelement_630]
sprite="mapfunction_sep,75"
category=category_1260
mapfunction=yes
show=both

// 631
[mapelement_631]
sprite="mapfunction_sep,76"
category=category_1222
mapfunction=yes
show=both

// 632
[mapelement_632]
sprite="mapfunction_sep,93"
category=category_1223
mapfunction=yes
show=both

// 633
[mapelement_633]
sprite="mapfunction_sep,77"
category=category_1224
mapfunction=yes
show=both

// 634
[mapelement_634]
sprite="mapfunction_sep,92"
category=category_1225
mapfunction=yes
show=both

// 635
[mapelement_635]
sprite="mapfunction_sep,94"
category=category_1226
mapfunction=yes
show=both

// 636
[mapelement_636]
sprite="mapfunction_sep,95"
category=category_1227
mapfunction=yes
show=both

// 637
[mapelement_637]
sprite="mapfunction_sep,78"
category=category_1228
mapfunction=yes
show=both

// 638
[mapelement_638]
sprite="mapfunction_sep,79"
mapfunction=yes
show=both

// 639
[mapelement_639]
sprite="mapfunction_sep,80"
mapfunction=yes
show=both

// 640
[mapelement_640]
sprite="mapfunction_sep,81"
mapfunction=yes
show=both

// 641
[mapelement_641]
sprite="mapfunction_sep,82"
mapfunction=yes
show=both

// 642
[mapelement_642]
sprite="mapfunction_sep,83"
mapfunction=yes
show=both

// 643
[mapelement_643]
sprite="mapfunction_sep,84"
mapfunction=yes
show=both

// 644
[mapelement_644]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_180,0,7

// 645
[mapelement_645]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_180,7,9999

// 646
[mapelement_646]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1850,0,5

// 647
[mapelement_647]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1850,5,9999

// 648
[mapelement_648]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_961,0,60

// 649
[mapelement_649]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_961,60,9999

// 650
[mapelement_650]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5331,0,35

// 651
[mapelement_651]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5331,35,9999

// 652
[mapelement_652]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5032,0,63

// 653
[mapelement_653]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5032,63,9999

// 654
[mapelement_654]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_148,0,11

// 655
[mapelement_655]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_148,11,9999

// 656
[mapelement_656]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3523,0,150

// 657
[mapelement_657]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3523,150,9999

// 658
[mapelement_658]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5733,0,60

// 659
[mapelement_659]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5733,60,9999

// 660
[mapelement_660]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_147,0,6

// 661
[mapelement_661]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_147,6,9999

// 662
[mapelement_662]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1404,0,127

// 663
[mapelement_663]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1404,127,9999

// 664
[mapelement_664]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5133,0,90

// 665
[mapelement_665]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5133,90,9999

// 666
[mapelement_666]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2326,0,90

// 667
[mapelement_667]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2326,90,9999

// 668
[mapelement_668]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1803,0,90

// 669
[mapelement_669]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1803,90,9999

// 670
[mapelement_670]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3550,0,11

// 671
[mapelement_671]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3550,11,9999

// 672
[mapelement_672]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_4105,0,18

// 673
[mapelement_673]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_4105,18,9999

// 674
[mapelement_674]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_451,0,2

// 675
[mapelement_675]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_451,2,9999

// 676
[mapelement_676]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1372,0,125

// 677
[mapelement_677]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1372,125,9999

// 678
[mapelement_678]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_532,0,11

// 679
[mapelement_679]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_532,11,9999

// 680
[mapelement_680]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2258,0,13

// 681
[mapelement_681]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2258,13,9999

// 682
[mapelement_682]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1938,0,110

// 683
[mapelement_683]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1938,110,9999

// 684
[mapelement_684]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_4684,0,150

// 685
[mapelement_685]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_4684,150,9999

// 686
[mapelement_686]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1051,0,10

// 687
[mapelement_687]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1051,10,9999

// 688
[mapelement_688]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3185,0,240

// 689
[mapelement_689]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3185,240,9999

// 690
[mapelement_690]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_334,0,28

// 691
[mapelement_691]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_334,28,9999

// 692
[mapelement_692]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_657,0,2

// 693
[mapelement_693]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_657,2,9999

// 694
[mapelement_694]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2610,0,14

// 695
[mapelement_695]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2610,14,9999

// 696
[mapelement_696]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5387,0,250

// 697
[mapelement_697]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5387,250,9999

// 698
[mapelement_698]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_302,0,61

// 699
[mapelement_699]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_302,60,9999

// 700
[mapelement_700]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both

// 701
[mapelement_701]
text=Kalphite<br>Hive
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 702
[mapelement_702]
text=Mobilising<br>Armies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 703
[mapelement_703]
sprite="mapfunction_sep,99"
mapfunction=yes
show=both

// 704
[mapelement_704]
sprite="mapfunction_sep,100"
mapfunction=yes
show=both

// 705
[mapelement_705]
sprite="mapfunction_sep,101"
mapfunction=yes
show=both

// 706
[mapelement_706]
sprite="mapfunction_sep,102"
mapfunction=yes
show=both

// 707
[mapelement_707]
sprite="mapfunction_sep,103"
category=category_1270
mapfunction=yes
show=both

// 708
[mapelement_708]
text=Aquanites
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 709
[mapelement_709]
sprite="mapdots_interface,1"
mapfunction=no
show=minimap

// 710
[mapelement_710]
text=Rogues'<br>Den
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 711
[mapelement_711]
text=Bag of<br>supplies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 712
[mapelement_712]
text=Pillars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 713
[mapelement_713]
text=Sleeping<br>dragon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 714
[mapelement_714]
text=Damaged<br>wall
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 715
[mapelement_715]
text=Rocks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 716
[mapelement_716]
text=Roots
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 717
[mapelement_717]
text=Roddeck's<br>hideout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 718
[mapelement_718]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 719
[mapelement_719]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 720
[mapelement_720]
text=Living<br>rock caverns
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 721
[mapelement_721]
sprite="mapfunction_sep,98"
category=category_1369
mapfunction=yes
show=both

// 722
[mapelement_722]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=minimap

// 723
[mapelement_723]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes

// 724
[mapelement_724]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 725
[mapelement_725]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 726
[mapelement_726]
text=Ancient cavern
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 727
[mapelement_727]
text=Mithril dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 728
[mapelement_728]
text=Hellhounds
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 729
[mapelement_729]
text=Greater demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 730
[mapelement_730]
text=Blue dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 731
[mapelement_731]
text=Gargoyles
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 732
[mapelement_732]
text=Abyssal demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 733
[mapelement_733]
text=Dark beasts
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 734
[mapelement_734]
text=Iron dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 735
[mapelement_735]
text=Steel dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 736
[mapelement_736]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=both
condition=varplayerbit_6884,2,2

// 737
[mapelement_737]
mapfunction=no
show=both
condition=varplayerbit_6913,5,5
condition2=varplayer_32,1,2
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 738
[mapelement_738]
mapfunction=no
show=both
condition=varplayerbit_6913,5,5
condition2=varplayer_32,1,2
polygonpoint0=15,13
polygonpoint1=15,44
polygonpoint2=50,44
polygonpoint3=50,13
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 739
[mapelement_739]
mapfunction=no
show=both
condition=varplayerbit_6913,13,13
condition2=varplayer_63,1,2
polygonpoint0=18,5
polygonpoint1=18,45
polygonpoint2=55,45
polygonpoint3=55,5
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 740
[mapelement_740]
mapfunction=no
show=both
condition=varplayerbit_6913,13,13
condition2=varplayer_63,3,4
polygonpoint0=0,-15
polygonpoint1=0,50
polygonpoint2=65,50
polygonpoint3=65,-15
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 741
[mapelement_741]
mapfunction=no
show=both
condition=varplayerbit_6913,13,13
condition2=varplayer_63,5,5
polygonpoint0=18,5
polygonpoint1=18,45
polygonpoint2=55,45
polygonpoint3=55,5
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 742
[mapelement_742]
mapfunction=no
show=both
condition=varplayerbit_6913,11,11
condition2=varplayer_107,1,4
polygonpoint0=34,-8
polygonpoint1=34,10
polygonpoint2=40,20
polygonpoint3=55,20
polygonpoint4=55,-13
polygonpoint5=35,-60
polygonpoint6=0,-60
polygonpoint7=0,-45
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 743
[mapelement_743]
mapfunction=no
show=both
condition=varplayerbit_6913,1,1
condition2=varplayer_29,1,1
polygonpoint0=-3,0
polygonpoint1=-3,57
polygonpoint2=-15,57
polygonpoint3=-50,92
polygonpoint4=-50,115
polygonpoint5=40,103
polygonpoint6=55,82
polygonpoint7=65,82
polygonpoint8=65,25
polygonpoint9=40,25
polygonpoint10=32,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 744
[mapelement_744]
text=Mill
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

// 745
[mapelement_745]
text=Chickens
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

// 746
[mapelement_746]
text=Chickens
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

// 747
[mapelement_747]
text=Cows
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

// 748
[mapelement_748]
text=Goblins
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

// 749
[mapelement_749]
text=Sheep
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

// 750
[mapelement_750]
text=Castle
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

// 751
[mapelement_751]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,1,39
polygonpoint0=0,0
polygonpoint1=0,11
polygonpoint2=10,11
polygonpoint3=10,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 752
[mapelement_752]
text=Start of<br>Black Knights' Fortress
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_130,0,0
condition2=varplayerbit_697,159,159

// 753
[mapelement_753]
text=Start of<br>Cook's Assistant
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_29,0,0
condition2=varplayerbit_697,1,1

// 754
[mapelement_754]
text=Start of<br>Demon Slayer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2561,0,0
condition2=varplayerbit_697,2,2

// 755
[mapelement_755]
text=Start of<br>Doric's Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_31,0,0
condition2=varplayerbit_697,3,3

// 756
[mapelement_756]
text=Start of<br>Dragon Slayer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_176,0,0
condition2=varplayerbit_697,4,4

// 757
[mapelement_757]
text=Start of<br>Ernest the Chicken
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_32,0,0
condition2=varplayerbit_697,5,5

// 758
[mapelement_758]
text=Start of<br>Goblin Diplomacy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2378,0,0
condition2=varplayerbit_697,6,6

// 759
[mapelement_759]
text=Start of<br>Imp Catcher
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_160,0,0
condition2=varplayerbit_697,7,7

// 760
[mapelement_760]
text=Start of<br>The Knight's Sword
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_122,0,0
condition2=varplayerbit_697,8,8

// 761
[mapelement_761]
text=Start of<br>Pirate's Treasure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_71,0,0
condition2=varplayerbit_697,9,9

// 762
[mapelement_762]
text=Start of<br>Prince Ali Rescue
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_273,0,0
condition2=varplayerbit_697,10,10

// 763
[mapelement_763]
text=Start of<br>The Restless Ghost
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_107,0,0
condition2=varplayerbit_697,11,11

// 764
[mapelement_764]
show=both
condition=varplayerbit_6913,174,174
condition2=varplayerbit_8248,2,6
polygonpoint0=0,0
polygonpoint1=0,11
polygonpoint2=25,11
polygonpoint3=25,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 765
[mapelement_765]
text=Start of<br>Rune Mysteries
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_63,0,0
condition2=varplayerbit_697,13,13

// 766
[mapelement_766]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,40,54
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=11,8
polygonpoint3=11,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 767
[mapelement_767]
text=Start of<br>Vampire Slayer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
op1=Scroll
condition=varplayer_178,0,0
condition2=varplayerbit_697,16,16
opbase=Start of Vampire Slayer

// 768
[mapelement_768]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,125,149
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=11,8
polygonpoint3=11,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 769
[mapelement_769]
text=Start of<br>Animal Magnetism
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3185,0,0
condition2=varplayerbit_697,18,18

// 770
[mapelement_770]
text=Start of<br>Between a Rock...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_299,0,0
condition2=varplayerbit_697,19,19

// 771
[mapelement_771]
text=Route to<br>Between a Rock...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_299,0,0
condition2=varplayerbit_697,19,19

// 772
[mapelement_772]
text=Start of<br>Big Chompy Bird Hunting
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_293,0,0
condition2=varplayerbit_697,20,20

// 773
[mapelement_773]
text=Start of<br>Biohazard
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_68,0,0
condition2=varplayerbit_697,21,21

// 774
[mapelement_774]
text=Start of<br>Cabin Fever
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_655,0,0
condition2=varplayerbit_697,22,22

// 775
[mapelement_775]
text=Start of<br>Clock Tower
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_10,0,0
condition2=varplayerbit_697,23,23

// 776
[mapelement_776]
text=Start of<br>Contact!
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3274,0,0
condition2=varplayerbit_697,24,24

// 777
[mapelement_777]
text=Start of<br>Zogre Flesh Eaters
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_487,0,0
condition2=varplayerbit_697,25,25

// 778
[mapelement_778]
text=Start of<br>Darkness of Hallowvale
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2573,0,0
condition2=varplayerbit_697,27,27

// 779
[mapelement_779]
text=Start of<br>Death to the Dorgeshuun
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
textbackgroundfill=0x2095c8ff
op1=Scroll
condition=varplayerbit_2258,0,0
condition2=varplayerbit_697,28,28
opbase=Start of Death to the Dorgeshuun

// 780
[mapelement_780]
text=Route to<br>Death to the Dorgeshuun
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
textbackgroundfill=0x2095c8ff
op1=Scroll
op2=Follow
condition=varplayerbit_2258,0,0
condition2=varplayerbit_697,28,28
opbase=Route to Death to the Dorgeshuun

// 781
[mapelement_781]
text=Start of<br>Death Plateau
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_314,0,0
condition2=varplayerbit_697,29,29

// 782
[mapelement_782]
text=Start of<br>Desert Treasure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_358,0,0
condition2=varplayerbit_697,30,30

// 783
[mapelement_783]
text=Start of<br>Devious Minds
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1465,0,0
condition2=varplayerbit_697,31,31

// 784
[mapelement_784]
text=Start of<br>The Dig Site
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_131,0,0
condition2=varplayerbit_697,32,32

// 785
[mapelement_785]
text=Start of<br>Druidic Ritual
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_80,0,0
condition2=varplayerbit_697,33,33

// 786
[mapelement_786]
text=Start of<br>Dwarf Cannon
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_0,0,0
condition2=varplayerbit_697,34,34

// 787
[mapelement_787]
text=Start of<br>Eadgar's Ruse
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_335,0,0
condition2=varplayerbit_697,35,35

// 788
[mapelement_788]
text=Start of<br>Eagles' Peak
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2780,0,0
condition2=varplayerbit_697,36,36

// 789
[mapelement_789]
text=Start of<br>Elemental Workshop II
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2639,0,0
condition2=varplayerbit_697,38,38

// 790
[mapelement_790]
text=Start of<br>Enakhra's Lament
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1560,0,0
condition2=varplayerbit_697,39,39

// 791
[mapelement_791]
text=Start of<br>Enlightened Journey
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2866,0,0
condition2=varplayerbit_697,40,40

// 792
[mapelement_792]
text=Start of<br>The Eyes of Glouphrie
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2497,0,0
condition2=varplayerbit_697,41,41

// 793
[mapelement_793]
text=Start of<br>Fairytale I - Growing Pains
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1803,0,0
condition2=varplayerbit_697,42,42

// 794
[mapelement_794]
text=Start of<br>Fairytale II - Cure a Queen
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2326,0,0
condition2=varplayerbit_697,43,43

// 795
[mapelement_795]
text=Start of<br>Family Crest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_148,0,0
condition2=varplayerbit_697,44,44

// 796
[mapelement_796]
text=Start of<br>The Feud
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_334,0,0
condition2=varplayerbit_697,45,45

// 797
[mapelement_797]
text=Start of<br>Fight Arena
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_17,0,0
condition2=varplayerbit_697,46,46

// 798
[mapelement_798]
text=Start of<br>Fishing Contest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_11,0,0
condition2=varplayerbit_697,47,47

// 799
[mapelement_799]
text=Start of<br>Forgettable Tale...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_822,0,0
condition2=varplayerbit_697,48,48

// 800
[mapelement_800]
text=Route to<br>Forgettable Tale...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_822,0,0
condition2=varplayerbit_697,48,48

// 801
[mapelement_801]
text=Start of<br>The Fremennik Trials
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_347,0,0
condition2=varplayerbit_697,49,49

// 802
[mapelement_802]
text=Start of<br>Waterfall Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_65,0,0
condition2=varplayerbit_697,50,50

// 803
[mapelement_803]
text=Start of<br>Garden of Tranquillity
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_961,0,0
condition2=varplayerbit_697,51,51

// 804
[mapelement_804]
text=Start of<br>Gertrude's Cat
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_180,0,0
condition2=varplayerbit_697,52,52

// 805
[mapelement_805]
text=Start of<br>Ghosts Ahoy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_217,0,0
condition2=varplayerbit_697,53,53

// 806
[mapelement_806]
text=Start of<br>The Giant Dwarf
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_571,0,0
condition2=varplayerbit_697,54,54

// 807
[mapelement_807]
text=Route of<br>The Giant Dwarf
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_571,0,0
condition2=varplayerbit_697,54,54

// 808
[mapelement_808]
text=Start of<br>The Golem
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_346,0,0
condition2=varplayerbit_697,55,55

// 809
[mapelement_809]
text=Start of<br>The Grand Tree
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_150,0,0
condition2=varplayerbit_697,56,56

// 810
[mapelement_810]
text=Start of<br>The Hand in the Sand
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1527,0,0
condition2=varplayerbit_697,57,57

// 811
[mapelement_811]
text=Start of<br>Haunted Mine
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_382,0,0
condition2=varplayerbit_697,58,58

// 812
[mapelement_812]
text=Start of<br>Hazeel Cult
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_223,0,0
condition2=varplayerbit_697,59,59

// 813
[mapelement_813]
text=Start of<br>Heroes' Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_188,0,0
condition2=varplayerbit_697,60,60

// 814
[mapelement_814]
text=Start of<br>Holy Grail
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_5,0,0
condition2=varplayerbit_697,61,61

// 815
[mapelement_815]
text=Start of<br>Horror from the Deep
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_34,0,0
condition2=varplayerbit_697,62,62

// 816
[mapelement_816]
text=Start of<br>Icthlarin's Little Helper
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_418,0,0
condition2=varplayerbit_697,63,63

// 817
[mapelement_817]
text=Start of<br>In Aid of the Myreque
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1990,0,0
condition2=varplayerbit_697,64,64

// 818
[mapelement_818]
text=Route to<br>In Aid of the Myreque
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1990,0,0
condition2=varplayerbit_697,64,64

// 819
[mapelement_819]
text=Start of<br>In Search of the Myreque
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_387,0,0
condition2=varplayerbit_697,65,65

// 820
[mapelement_820]
text=Start of<br>Jungle Potion
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_175,0,0
condition2=varplayerbit_697,66,66

// 821
[mapelement_821]
text=Start of<br>Legends' Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_139,0,0
condition2=varplayerbit_697,67,67

// 822
[mapelement_822]
text=Start of<br>Lost City
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_147,0,0
condition2=varplayerbit_697,68,68

// 823
[mapelement_823]
text=Start of<br>The Lost Tribe
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_532,0,0
condition2=varplayerbit_697,69,69

// 824
[mapelement_824]
text=Start of<br>Lunar Diplomacy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2448,0,0
condition2=varplayerbit_697,70,70

// 825
[mapelement_825]
text=Start of<br>Making History
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1383,0,0
condition2=varplayerbit_697,71,71

// 826
[mapelement_826]
text=Start of<br>Merlin's Crystal
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_14,0,0
condition2=varplayerbit_697,72,72

// 827
[mapelement_827]
text=Start of<br>Monkey Madness
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_365,0,0
condition2=varplayerbit_697,73,73

// 828
[mapelement_828]
text=Start of<br>Monk's Friend
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_30,0,0
condition2=varplayerbit_697,74,74

// 829
[mapelement_829]
text=Start of<br>Mountain Daughter
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_260,0,0
condition2=varplayerbit_697,75,75

// 830
[mapelement_830]
text=Start of<br>Mourning's Ends Part I
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_517,0,0
condition2=varplayerbit_697,76,76

// 831
[mapelement_831]
text=Start of<br>Mourning's Ends Part II
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1103,0,8
condition2=varplayerbit_697,77,77

// 832
[mapelement_832]
text=Start of<br>Within the Light
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6553,0,0
condition2=varplayerbit_697,161,161

// 833
[mapelement_833]
text=Start of<br>Murder Mystery
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_192,0,0
condition2=varplayerbit_697,78,78

// 834
[mapelement_834]
text=Start of<br>My Arm's Big Adventure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2790,0,0
condition2=varplayerbit_697,79,79

// 835
[mapelement_835]
text=Route to<br>My Arm's Big Adventure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2790,0,0
condition2=varplayerbit_697,79,79

// 836
[mapelement_836]
text=Start of<br>Nature Spirit
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_307,0,0
condition2=varplayerbit_697,80,80

// 837
[mapelement_837]
text=Route to<br>Nature Spirit
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_307,0,0
condition2=varplayerbit_697,80,80

// 838
[mapelement_838]
text=Start of<br>Observatory Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_112,0,0
condition2=varplayerbit_697,81,81

// 839
[mapelement_839]
text=Start of<br>One Small Favour
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_416,0,0
condition2=varplayerbit_697,82,82

// 840
[mapelement_840]
text=Start of<br>Plague City
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_165,0,0
condition2=varplayerbit_697,83,83

// 841
[mapelement_841]
text=Start of<br>Priest in Peril
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_302,0,0
condition2=varplayerbit_697,84,84

// 842
[mapelement_842]
text=Start of<br>Rag and Bone Man
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_714,0,0
condition2=varplayerbit_697,85,85

// 843
[mapelement_843]
text=Start of<br>Ratcatchers
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1404,0,0
condition2=varplayerbit_697,86,86

// 844
[mapelement_844]
text=Start of<br>Recipe for Disaster
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1850,0,0
condition2=varplayerbit_697,87,87

// 845
[mapelement_845]
text=Start of<br>Recruitment Drive
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_657,0,0
condition2=varplayerbit_697,88,88

// 846
[mapelement_846]
text=Start of<br>Roving Elves
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_402,0,0
condition2=varplayerbit_697,90,90

// 847
[mapelement_847]
text=Start of<br>Royal Trouble
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2140,0,0
condition2=varplayerbit_697,91,91

// 848
[mapelement_848]
text=Start of<br>Rum Deal
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_600,0,0
condition2=varplayerbit_697,92,92

// 849
[mapelement_849]
text=Start of<br>Scorpion Catcher
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_76,0,0
condition2=varplayerbit_697,93,93

// 850
[mapelement_850]
text=Start of<br>Sea Slug
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_159,0,0
condition2=varplayerbit_697,94,94

// 851
[mapelement_851]
text=Start of<br>The Slug Menace
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2610,0,0
condition2=varplayerbit_697,95,95

// 852
[mapelement_852]
text=Start of<br>Shades of Mort'ton
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_339,0,0
condition2=varplayerbit_697,96,96

// 853
[mapelement_853]
text=Start of<br>Shadow of the Storm
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1372,0,0
condition2=varplayerbit_697,97,97

// 854
[mapelement_854]
text=Start of<br>Sheep Herder
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_60,0,0
condition2=varplayerbit_697,98,98

// 855
[mapelement_855]
text=Start of<br>Shilo Village
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_116,0,0
condition2=varplayerbit_697,99,99

// 856
[mapelement_856]
text=Start of<br>A Soul's Bane
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2011,0,0
condition2=varplayerbit_697,100,100

// 857
[mapelement_857]
text=Start of<br>Spirits of the Elid
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1444,0,0
condition2=varplayerbit_697,101,101

// 858
[mapelement_858]
text=Start of<br>Swan Song
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2098,0,0
condition2=varplayerbit_697,102,102

// 859
[mapelement_859]
text=Start of<br>Tai Bwo Wannai Trio
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_320,0,2
condition2=varplayerbit_697,103,103

// 860
[mapelement_860]
text=Start of<br>A Tail of Two Cats
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1028,0,0
condition2=varplayerbit_697,104,104

// 861
[mapelement_861]
text=Start of<br>Tears of Guthix
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_451,0,0
condition2=varplayerbit_697,105,105

// 862
[mapelement_862]
text=Route to<br>Tears of Guthix
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_451,0,0
condition2=varplayerbit_697,105,105

// 863
[mapelement_863]
text=Start of<br>Temple of Ikov
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_26,0,0
condition2=varplayerbit_697,106,106

// 864
[mapelement_864]
text=Start of<br>Throne of Miscellania
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_359,0,0
condition2=varplayerbit_697,107,107

// 865
[mapelement_865]
text=Start of<br>The Tourist Trap
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_197,0,0
condition2=varplayerbit_697,108,108

// 866
[mapelement_866]
text=Start of<br>Witch's House
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_226,0,0
condition2=varplayerbit_697,109,109

// 867
[mapelement_867]
text=Start of<br>Tree Gnome Village
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_111,0,0
condition2=varplayerbit_697,110,110

// 868
[mapelement_868]
text=Start of<br>Tribal Totem
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_200,0,0
condition2=varplayerbit_697,111,111

// 869
[mapelement_869]
text=Start of<br>Troll Romance
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_385,0,0
condition2=varplayerbit_697,112,112

// 870
[mapelement_870]
text=Route to<br>Troll Romance
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_385,0,0
condition2=varplayerbit_697,112,112

// 871
[mapelement_871]
text=Start of<br>Troll Stronghold
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_317,0,0
condition2=varplayerbit_697,113,113

// 872
[mapelement_872]
text=Start of<br>Wanted!
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1051,0,0
condition2=varplayerbit_697,115,115

// 873
[mapelement_873]
text=Start of<br>Watchtower
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_212,0,0
condition2=varplayerbit_697,116,116

// 874
[mapelement_874]
text=Start of<br>Cold War
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3293,0,0
condition2=varplayerbit_697,117,117

// 875
[mapelement_875]
text=Start of<br>The Fremennik Isles
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3311,0,0
condition2=varplayerbit_697,118,118

// 876
[mapelement_876]
text=Start of<br>Tower of Life
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3337,0,0
condition2=varplayerbit_697,119,119

// 877
[mapelement_877]
text=Start of<br>The Great Brain Robbery
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_980,0,0
condition2=varplayerbit_697,120,120

// 878
[mapelement_878]
text=Start of<br>What Lies Below
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3523,0,0
condition2=varplayerbit_697,121,121

// 879
[mapelement_879]
text=Start of<br>Olaf's Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3534,0,0
condition2=varplayerbit_697,122,122

// 880
[mapelement_880]
text=Start of<br>Another Slice of H.A.M.
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3550,0,0
condition2=varplayerbit_697,123,123

// 881
[mapelement_881]
text=Route to<br>Another Slice of H.A.M.
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3550,0,0
condition2=varplayerbit_697,123,123

// 882
[mapelement_882]
text=Start of<br>Dream Mentor
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3618,0,0
condition2=varplayerbit_697,124,124

// 883
[mapelement_883]
text=Route to<br>Dream Mentor
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3618,0,0
condition2=varplayerbit_697,124,124

// 884
[mapelement_884]
text=Start of<br>Grim Tales
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2783,0,0
condition2=varplayerbit_697,125,125

// 885
[mapelement_885]
text=Start of<br>King's Ransom
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3888,0,0
condition2=varplayerbit_697,126,126

// 886
[mapelement_886]
text=Start of<br>The Path of Glouphrie
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3954,0,0
condition2=varplayerbit_697,127,127

// 887
[mapelement_887]
text=Start of<br>Back to my Roots
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4055,0,0
condition2=varplayerbit_697,128,128

// 888
[mapelement_888]
text=Start of<br>Land of the Goblins
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4105,0,0
condition2=varplayerbit_697,129,129

// 889
[mapelement_889]
text=Route to<br>Land of the Goblins
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4105,0,0
condition2=varplayerbit_697,129,129

// 890
[mapelement_890]
text=Start of<br>Dealing with Scabaras
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4230,0,0
condition2=varplayerbit_697,130,130

// 891
[mapelement_891]
text=Start of<br>Wolf Whistle
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4302,0,0
condition2=varplayerbit_697,131,131

// 892
[mapelement_892]
text=Start of<br>As a First Resort
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4321,0,9
condition2=varplayerbit_697,132,132

// 893
[mapelement_893]
text=Start of<br>Catapult Construction
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4396,0,0
condition2=varplayerbit_697,133,133

// 894
[mapelement_894]
text=Start of<br>Kennith's Concerns
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4505,0,0
condition2=varplayerbit_697,134,134

// 895
[mapelement_895]
text=Start of<br>Legacy of Seergaze
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4569,0,0
condition2=varplayerbit_697,135,135

// 896
[mapelement_896]
text=Start of<br>Perils of Ice Mountain
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4684,0,0
condition2=varplayerbit_697,136,136

// 897
[mapelement_897]
text=Start of<br>TokTz-Ket-Dill
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4700,0,0
condition2=varplayerbit_697,137,137

// 898
[mapelement_898]
text=Route to<br>TokTz-Ket-Dill
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4700,0,0
condition2=varplayerbit_697,137,137

// 899
[mapelement_899]
text=Start of<br>Smoking Kills
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4764,0,0
condition2=varplayerbit_697,138,138

// 900
[mapelement_900]
text=Start of<br>Rocking Out
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4797,0,0
condition2=varplayerbit_697,139,139

// 901
[mapelement_901]
text=Start of<br>Spirit of Summer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5032,0,0
condition2=varplayerbit_697,140,140

// 902
[mapelement_902]
text=Start of<br>Meeting History
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5075,0,0
condition2=varplayerbit_697,141,141

// 903
[mapelement_903]
text=Start of<br>All Fired Up
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5133,0,0
condition2=varplayerbit_697,142,142

// 904
[mapelement_904]
text=Start of<br>Summer's End
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5331,0,0
condition2=varplayerbit_697,143,143

// 905
[mapelement_905]
text=Start of<br>Defender of Varrock
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5387,0,0
condition2=varplayerbit_697,144,144

// 906
[mapelement_906]
text=Start of<br>While Guthix Sleeps
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5491,0,0
condition2=varplayerbit_697,145,145

// 907
[mapelement_907]
text=Start of<br>In Pyre Need
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5761,0,0
condition2=varplayerbit_697,146,146

// 908
[mapelement_908]
text=Start of<br>Myths of the White Lands
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5733,0,0
condition2=varplayerbit_697,148,148

// 909
[mapelement_909]
text=Start of<br>Glorious Memories
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6001,0,2
condition2=varplayerbit_697,149,149

// 910
[mapelement_910]
text=Start of<br>The Tale of the Muspah
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6048,0,5
condition2=varplayerbit_697,150,150

// 911
[mapelement_911]
text=Start of<br>Missing My Mummy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6112,0,0
condition2=varplayerbit_697,155,155

// 912
[mapelement_912]
text=Start of<br>The Curse of Arrav
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6289,0,0
condition2=varplayerbit_697,156,156

// 913
[mapelement_913]
text=Start of<br>The Temple at Senntisten
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6775,0,0
condition2=varplayerbit_697,157,157

// 914
[mapelement_914]
text=Start of<br>Hunt for Red Raktuber
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6180,0,1
condition2=varplayerbit_697,151,151

// 915
[mapelement_915]
text=Start of<br>The Chosen Commander
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1938,0,0
condition2=varplayerbit_697,152,152

// 916
[mapelement_916]
text=Route to<br>The Chosen Commander
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1938,0,0
condition2=varplayerbit_697,152,152

// 917
[mapelement_917]
text=Start of<br>Swept Away
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5448,0,0
condition2=varplayerbit_697,153,153

// 918
[mapelement_918]
text=Start of<br>Nomad's Requiem
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6962,0,0
condition2=varplayerbit_697,162,162

// 919
[mapelement_919]
text=Start of<br>Blood Runs Deep
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6883,0,1
condition2=varplayerbit_697,163,163

// 920
[mapelement_920]
sprite="mapdots_interface,0"
mapfunction=no
show=minimap

// 921
[mapelement_921]
text=Start of<br>The Blood Pact
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7238,0,0
condition2=varplayerbit_697,170,170

// 922
[mapelement_922]
text=Daemonheim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 923
[mapelement_923]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7792,0,0
polygonpoint0=-12,39
polygonpoint1=33,39
polygonpoint2=33,71
polygonpoint3=-12,71
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 924
[mapelement_924]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7792,5,5
polygonpoint0=19,-2
polygonpoint1=28,-2
polygonpoint2=28,6
polygonpoint3=19,6
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 925
[mapelement_925]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7793,7,25
polygonpoint0=-3,1
polygonpoint1=-3,37
polygonpoint2=31,37
polygonpoint3=31,1
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 926
[mapelement_926]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7793,10,25
polygonpoint0=-1,8
polygonpoint1=-1,20
polygonpoint2=13,20
polygonpoint3=13,8
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 927
[mapelement_927]
text=Start of<br>Buyers and Cellars
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7792,0,0
condition2=varplayerbit_697,167,167

// 928
[mapelement_928]
text=Start of<br>Elemental Workshop III
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7871,0,0
condition2=varplayerbit_697,172,172

// 929
[mapelement_929]
show=both
condition=varplayerbit_6913,172,172
condition2=varplayerbit_7871,0,4
polygonpoint0=-10,10
polygonpoint1=10,10
polygonpoint2=10,-30
polygonpoint3=-10,-30
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 930
[mapelement_930]
text=Start of<br>Fairy Tale III
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7826,0,0
condition2=varplayerbit_697,158,158

// 931
[mapelement_931]
text=Start of<br>Quiet Before the Swarm
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7958,0,0
condition2=varplayerbit_697,171,171

// 932
[mapelement_932]
mapfunction=no
show=both
condition=varplayerbit_6913,170,170
condition2=varplayerbit_7238,1,59
polygonpoint0=-6,-8
polygonpoint1=-6,6
polygonpoint2=8,6
polygonpoint3=8,-8
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 933
[mapelement_933]
show=both
condition=varplayerbit_6913,171,171
condition2=varplayerbit_7958,5,85
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 934
[mapelement_934]
show=both
condition=varplayerbit_6913,171,171
condition2=varplayerbit_7958,5,85
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 935
[mapelement_935]
show=both
condition=varplayerbit_6913,171,171
condition2=varplayerbit_7958,0,85
polygonpoint0=-10,-15
polygonpoint1=-20,-5
polygonpoint2=-20,15
polygonpoint3=-10,20
polygonpoint4=10,20
polygonpoint5=20,15
polygonpoint6=20,-5
polygonpoint7=10,-15
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 936
[mapelement_936]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 937
[mapelement_937]
mapfunction=no
show=both
condition=varplayerbit_6913,153,153
condition2=varplayerbit_5448,1,49
polygonpoint0=-8,-5
polygonpoint1=-8,5
polygonpoint2=8,5
polygonpoint3=8,-5
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 938
[mapelement_938]
mapfunction=no
show=both
condition=varplayerbit_6913,153,153
condition2=varplayerbit_5448,20,29
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=8,8
polygonpoint3=8,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 939
[mapelement_939]
mapfunction=no
show=both
condition=varplayerbit_6913,153,153
condition2=varplayerbit_5448,20,29
polygonpoint0=0,0
polygonpoint1=0,10
polygonpoint2=8,10
polygonpoint3=8,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 940
[mapelement_940]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,1,9
polygonpoint0=0,0
polygonpoint1=0,7
polygonpoint2=7,7
polygonpoint3=7,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 941
[mapelement_941]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,50,59
polygonpoint0=0,0
polygonpoint1=0,7
polygonpoint2=7,7
polygonpoint3=7,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 942
[mapelement_942]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,10,49
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=9,8
polygonpoint3=9,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 943
[mapelement_943]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,10,49
polygonpoint0=0,0
polygonpoint1=0,9
polygonpoint2=11,9
polygonpoint3=11,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 944
[mapelement_944]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,55,124
polygonpoint0=17,0
polygonpoint1=17,-16
polygonpoint2=0,-16
polygonpoint3=0,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 945
[mapelement_945]
text=Start of<br>Love Story
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_8045,0,0
condition2=varplayerbit_697,168,168

// 946
[mapelement_946]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 947
[mapelement_947]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 948
[mapelement_948]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 949
[mapelement_949]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 950
[mapelement_950]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 951
[mapelement_951]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 952
[mapelement_952]
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,1,1
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 953
[mapelement_953]
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,60,60
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 954
[mapelement_954]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,3,15
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 955
[mapelement_955]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,16,24
polygonpoint0=-30,0
polygonpoint1=40,0
polygonpoint2=40,23
polygonpoint3=17,42
polygonpoint4=-14,46
polygonpoint5=-30,41
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 956
[mapelement_956]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,27,30
polygonpoint0=-24,20
polygonpoint1=-24,0
polygonpoint2=-3,0
polygonpoint3=-3,-3
polygonpoint4=10,-3
polygonpoint5=10,20
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 957
[mapelement_957]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,33,48
polygonpoint0=-4,5
polygonpoint1=-13,-1
polygonpoint2=-14,-13
polygonpoint3=7,-27
polygonpoint4=33,-27
polygonpoint5=32,-13
polygonpoint6=20,-7
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 958
[mapelement_958]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,51,57
polygonpoint0=-6,0
polygonpoint1=-6,22
polygonpoint2=16,22
polygonpoint3=16,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 959
[mapelement_959]
text=Start of<br>A Void Dance
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7451,1,1
condition2=varplayerbit_697,173,173

// 960
[mapelement_960]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 961
[mapelement_961]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 962
[mapelement_962]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 963
[mapelement_963]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 964
[mapelement_964]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 965
[mapelement_965]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 966
[mapelement_966]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 967
[mapelement_967]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 968
[mapelement_968]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 969
[mapelement_969]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 970
[mapelement_970]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 971
[mapelement_971]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 972
[mapelement_972]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 973
[mapelement_973]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 974
[mapelement_974]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 975
[mapelement_975]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 976
[mapelement_976]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 977
[mapelement_977]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 978
[mapelement_978]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 979
[mapelement_979]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 980
[mapelement_980]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 981
[mapelement_981]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 982
[mapelement_982]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 983
[mapelement_983]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 984
[mapelement_984]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 985
[mapelement_985]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 986
[mapelement_986]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 987
[mapelement_987]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 988
[mapelement_988]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 989
[mapelement_989]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 990
[mapelement_990]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 991
[mapelement_991]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 992
[mapelement_992]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 993
[mapelement_993]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 994
[mapelement_994]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 995
[mapelement_995]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 996
[mapelement_996]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

// 997
[mapelement_997]
text=(Barbarian Village)
textsize=0
textcolour=0xcccccc
mapfunction=yes
category=category_950
condition=varplayerbit_5819,1,1

// 998
[mapelement_998]
text=Gunnarsgrunn
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950
condition=varplayerbit_5819,1,1

// 999
[mapelement_999]
show=both
condition=varplayerbit_6913,17,17
condition2=varplayerbit_5730,1,99
polygonpoint0=0,0
polygonpoint1=0,102
polygonpoint2=43,102
polygonpoint3=43,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1000
[mapelement_1000]
text=Start of<br>Gunnar's Ground
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5730,0,0
condition2=varplayerbit_697,17,17

// 1001
[mapelement_1001]
show=both
condition=varplayerbit_6913,174,174
condition2=varplayerbit_8248,8,38
polygonpoint0=0,0
polygonpoint1=0,15
polygonpoint2=15,15
polygonpoint3=15,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1002
[mapelement_1002]
show=both
condition=varplayerbit_6913,174,174
condition2=varplayerbit_8248,8,38
polygonpoint0=0,0
polygonpoint1=0,50
polygonpoint2=50,50
polygonpoint3=50,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1003
[mapelement_1003]
text=Start of<br>The Void Stares Back
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_8248,0,0
condition2=varplayerbit_697,174,174

// 1004
[mapelement_1004]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,10,10
polygonpoint0=0,0
polygonpoint1=0,30
polygonpoint2=25,30
polygonpoint3=25,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1005
[mapelement_1005]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,15,15
polygonpoint0=0,0
polygonpoint1=0,62
polygonpoint2=53,62
polygonpoint3=53,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1006
[mapelement_1006]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,17,17
polygonpoint0=0,0
polygonpoint1=0,30
polygonpoint2=25,30
polygonpoint3=25,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1007
[mapelement_1007]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,25,75
polygonpoint0=0,0
polygonpoint1=0,126
polygonpoint2=128,126
polygonpoint3=128,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1008
[mapelement_1008]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,80,90
polygonpoint0=0,0
polygonpoint1=0,62
polygonpoint2=58,62
polygonpoint3=58,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1009
[mapelement_1009]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,90,100
polygonpoint0=0,0
polygonpoint1=0,126
polygonpoint2=128,126
polygonpoint3=128,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1010
[mapelement_1010]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,105,105
polygonpoint0=0,0
polygonpoint1=64,0
polygonpoint2=64,-128
polygonpoint3=319,-128
polygonpoint4=319,128
polygonpoint5=384,128
polygonpoint6=384,231
polygonpoint7=291,294
polygonpoint8=182,253
polygonpoint9=72,243
polygonpoint10=0,164
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1011
[mapelement_1011]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,110,115
polygonpoint0=0,0
polygonpoint1=0,17
polygonpoint2=17,17
polygonpoint3=17,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1012
[mapelement_1012]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,120,130
polygonpoint0=0,0
polygonpoint1=0,74
polygonpoint2=66,74
polygonpoint3=66,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1013
[mapelement_1013]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,135,150
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1014
[mapelement_1014]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,155,190
polygonpoint0=0,0
polygonpoint1=64,0
polygonpoint2=64,-128
polygonpoint3=319,-128
polygonpoint4=319,128
polygonpoint5=384,128
polygonpoint6=384,231
polygonpoint7=291,294
polygonpoint8=182,253
polygonpoint9=72,243
polygonpoint10=0,164
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1015
[mapelement_1015]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,195,220
polygonpoint0=0,0
polygonpoint1=0,17
polygonpoint2=17,17
polygonpoint3=17,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1016
[mapelement_1016]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,215,215
polygonpoint0=0,0
polygonpoint1=0,126
polygonpoint2=128,126
polygonpoint3=128,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1017
[mapelement_1017]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,225,230
polygonpoint0=0,0
polygonpoint1=0,30
polygonpoint2=25,30
polygonpoint3=25,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1018
[mapelement_1018]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,235,245
polygonpoint0=0,0
polygonpoint1=0,17
polygonpoint2=17,17
polygonpoint3=17,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1019
[mapelement_1019]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,250,255
polygonpoint0=0,0
polygonpoint1=0,66
polygonpoint2=42,66
polygonpoint3=42,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1020
[mapelement_1020]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,260,260
polygonpoint0=0,0
polygonpoint1=0,17
polygonpoint2=17,17
polygonpoint3=17,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1021
[mapelement_1021]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,265,275
polygonpoint0=0,0
polygonpoint1=0,40
polygonpoint2=32,40
polygonpoint3=32,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1022
[mapelement_1022]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,280,280
polygonpoint0=0,0
polygonpoint1=0,17
polygonpoint2=17,17
polygonpoint3=17,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1023
[mapelement_1023]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,285,290
polygonpoint0=0,0
polygonpoint1=0,42
polygonpoint2=50,42
polygonpoint3=50,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1024
[mapelement_1024]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,295,305
polygonpoint0=0,0
polygonpoint1=0,17
polygonpoint2=17,17
polygonpoint3=17,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1025
[mapelement_1025]
show=both
condition=varplayerbit_6913,179,179
condition2=varplayerbit_8605,310,310
polygonpoint0=0,0
polygonpoint1=0,30
polygonpoint2=25,30
polygonpoint3=25,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1026
[mapelement_1026]
text=Start of<br>Do No Evil
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_8605,0,5
condition2=varplayerbit_697,179,179

// 1027
[mapelement_1027]
text=Ancient<br>Prison
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1028
[mapelement_1028]
sprite="mapfunction_sep,104"
category=category_2098
mapfunction=yes
show=both

// 1029
[mapelement_1029]
show=both
condition=varplayerbit_6913,14,14
condition2=varplayerbit_8704,10,59
polygonpoint0=0,64
polygonpoint1=80,28
polygonpoint2=128,28
polygonpoint3=128,120
polygonpoint4=0,120
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1030
[mapelement_1030]
show=both
condition=varplayerbit_6913,14,14
condition2=varplayerbit_8704,60,79
polygonpoint0=40,16
polygonpoint1=40,-8
polygonpoint2=64,-8
polygonpoint3=64,16
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1031
[mapelement_1031]
show=both
condition=varplayerbit_6913,14,14
condition2=varplayerbit_8704,80,89
polygonpoint0=0,64
polygonpoint1=80,28
polygonpoint2=128,28
polygonpoint3=128,120
polygonpoint4=0,120
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1032
[mapelement_1032]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1033
[mapelement_1033]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1034
[mapelement_1034]
text=Forinthry Dungeon
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1035
[mapelement_1035]
text=Green dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1036
[mapelement_1036]
text=Revenants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1037
[mapelement_1037]
text=Ankous
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1038
[mapelement_1038]
text=Boneyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1039
[mapelement_1039]
text=Gamers'<br>Grotto
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1040
[mapelement_1040]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1041
[mapelement_1041]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1042
[mapelement_1042]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 1043
[mapelement_1043]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 1044
[mapelement_1044]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 1045
[mapelement_1045]
show=both
condition=varplayerbit_6913,12,12
condition2=varplayerbit_5332,115,115
polygonpoint0=0,0
polygonpoint1=0,64
polygonpoint2=64,64
polygonpoint3=64,0
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1046
[mapelement_1046]
show=both
condition=varplayerbit_6913,12,12
condition2=varplayerbit_5332,30,55
polygonpoint0=5,10
polygonpoint1=5,64
polygonpoint2=64,64
polygonpoint3=64,10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1047
[mapelement_1047]
show=both
condition=varplayerbit_6913,12,12
condition2=varplayerbit_5332,15,20
polygonpoint0=-5,-5
polygonpoint1=-5,15
polygonpoint2=15,15
polygonpoint3=15,-5
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1048
[mapelement_1048]
show=both
condition=varplayerbit_6913,12,12
condition2=varplayerbit_5332,25,28
polygonpoint0=-5,10
polygonpoint1=-5,123
polygonpoint2=69,123
polygonpoint3=69,59
polygonpoint4=44,10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1049
[mapelement_1049]
show=both
condition=varplayerbit_6913,12,12
condition2=varplayerbit_5332,60,110
polygonpoint0=-5,10
polygonpoint1=-5,123
polygonpoint2=69,123
polygonpoint3=69,59
polygonpoint4=44,10
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1050
[mapelement_1050]
text=Start of<br>The Prisoner of Glouphrie
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5332,0,0
condition2=varplayerbit_697,12,12

// 1051
[mapelement_1051]
show=both
condition=varplayerbit_6913,180,180
condition2=varplayerbit_998,0,9
polygonpoint0=-10,10
polygonpoint1=10,10
polygonpoint2=10,-90
polygonpoint3=-10,-90
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1052
[mapelement_1052]
text=Artisan<br>Workshop
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1053
[mapelement_1053]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 1054
[mapelement_1054]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 1055
[mapelement_1055]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1056
[mapelement_1056]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1057
[mapelement_1057]
show=both
condition=varplayerbit_6913,181,181
condition2=varplayerbit_8961,0,200
polygonpoint0=7,7
polygonpoint1=7,-7
polygonpoint2=-7,-7
polygonpoint3=-7,7
polygonpoint4=7,7
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1058
[mapelement_1058]
show=both
condition=varplayerbit_6913,181,181
condition2=varplayerbit_8961,45,200
polygonpoint0=3,3
polygonpoint1=3,-3
polygonpoint2=-3,-3
polygonpoint3=-3,3
polygonpoint4=3,3
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1059
[mapelement_1059]
show=both
condition=varplayerbit_6913,181,181
condition2=varplayerbit_8961,110,200
polygonpoint0=10,3
polygonpoint1=10,-3
polygonpoint2=-10,-3
polygonpoint3=-10,3
polygonpoint4=10,3
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1060
[mapelement_1060]
show=both
condition=varplayerbit_6913,181,181
condition2=varplayerbit_8961,65,80
polygonpoint0=2,2
polygonpoint1=2,-2
polygonpoint2=-2,-2
polygonpoint3=-2,2
polygonpoint4=2,2
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1061
[mapelement_1061]
show=both
condition=varplayerbit_6913,181,181
condition2=varplayerbit_8961,75,80
polygonpoint0=2,2
polygonpoint1=2,-2
polygonpoint2=-2,-2
polygonpoint3=-2,2
polygonpoint4=2,2
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1062
[mapelement_1062]
sprite="mapfunction_sep,105"
mapfunction=yes
category=category_2173
show=both

// 1063
[mapelement_1063]
sprite="mapfunction_sep,106"
mapfunction=yes
category=category_2174
show=both

// 1064
[mapelement_1064]
sprite="mapfunction_sep,107"
mapfunction=yes
category=category_2175
show=both

// 1065
[mapelement_1065]
sprite="mapfunction_sep,108"
mapfunction=yes
category=category_2176
show=both

// 1066
[mapelement_1066]
sprite="mapfunction_sep,109"
mapfunction=yes
category=category_2177
show=both

// 1067
[mapelement_1067]
text=Clan Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1068
[mapelement_1068]
text=Start of<br>Elemental Workshop IV
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_998,0,0
condition2=varplayerbit_697,180,180

// 1069
[mapelement_1069]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1070
[mapelement_1070]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1071
[mapelement_1071]
show=both
condition=varplayerbit_6913,182,182
condition2=varplayerbit_9369,0,35
polygonpoint0=15,-5
polygonpoint1=15,45
polygonpoint2=63,45
polygonpoint3=63,-5
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1072
[mapelement_1072]
show=both
condition=varplayerbit_6913,182,182
condition2=varplayerbit_9369,45,45
polygonpoint0=15,-5
polygonpoint1=15,45
polygonpoint2=63,45
polygonpoint3=63,-5
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1073
[mapelement_1073]
show=both
condition=varplayerbit_6913,182,182
condition2=varplayerbit_9370,1,2
polygonpoint0=5,5
polygonpoint1=5,32
polygonpoint2=50,32
polygonpoint3=50,5
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1074
[mapelement_1074]
show=both
condition=varplayerbit_6913,182,182
condition2=varplayerbit_9372,2,2
polygonpoint0=3,15
polygonpoint1=3,32
polygonpoint2=28,32
polygonpoint3=28,15
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1075
[mapelement_1075]
sprite="mapfunction_sep,111"
category=category_2270
mapfunction=yes
show=both

// 1076
[mapelement_1076]
show=both
condition=varplayerbit_6913,182,182
condition2=varplayerbit_9369,40,40
polygonpoint0=3,15
polygonpoint1=3,32
polygonpoint2=28,32
polygonpoint3=28,15
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1077
[mapelement_1077]
text=Start of<br>Deadliest Catch
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_9369,0,0
condition2=varplayerbit_697,182,182

// 1078
[mapelement_1078]
show=both
condition=varplayerbit_6913,183,183
condition2=varplayerbit_9491,0,80
polygonpoint0=51,43
polygonpoint1=26,43
polygonpoint2=26,58
polygonpoint3=51,58
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1079
[mapelement_1079]
show=both
condition=varplayerbit_6913,183,183
condition2=varplayerbit_9491,85,250
polygonpoint0=29,38
polygonpoint1=29,42
polygonpoint2=33,42
polygonpoint3=33,38
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1080
[mapelement_1080]
show=both
condition=varplayerbit_6913,183,183
condition2=varplayerbit_9491,85,250
polygonpoint0=7,6
polygonpoint1=7,30
polygonpoint2=44,30
polygonpoint3=44,6
polygonfill=0x33aeffff
polygonoutline=0xff00ffff

// 1081
[mapelement_1081]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 1082
[mapelement_1082]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

// 1083
[mapelement_1083]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1084
[mapelement_1084]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

// 1085
[mapelement_1085]
text=Mutated<br>jadinko<br>babies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1086
[mapelement_1086]
text=Mutated<br>jadinko<br>guards
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1087
[mapelement_1087]
text=Mutated<br>jadinko<br>males
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

// 1088
[mapelement_1088]
text=Jadinko<br>Queen
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

