[mapelement_0]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_1]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_2]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_3]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_4]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_5]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_6]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_7]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_8]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_9]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_10]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_11]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_12]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_13]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_14]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_15]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_16]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_17]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_18]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_19]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_20]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_21]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_22]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_23]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_24]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_25]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_26]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_27]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_28]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_29]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_30]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_31]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_32]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_33]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_34]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_35]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_36]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_37]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_38]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_39]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_40]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_41]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_42]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_43]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_44]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_45]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_46]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_47]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_48]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_49]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_50]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_51]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_52]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_53]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_54]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_55]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_56]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_57]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_58]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_59]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_60]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_61]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_62]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_63]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_64]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_65]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_66]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_67]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_68]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_69]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_70]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_71]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_72]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_73]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_74]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_75]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_76]
text=Exit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_77]
text=East Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_78]
text=West Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_79]
text=Soul Obelisk
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950
show=both

[mapelement_80]
text=Entrance
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_81]
text=Exit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_82]
text=Lumbridge
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_83]
text=Varrock
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_84]
text=Kingdom of<br>Misthalin
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_85]
text=Al Kharid
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_86]
text=Duel<br>Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_87]
text=Shantay<br>Pass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_88]
text=Toll<br>Gate
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_89]
text=Tutorial Island
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_90]
text=Port<br>Sarim
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_91]
text=Falador
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_92]
text=Edgeville
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_93]
text=Brimhaven
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_94]
text=Karamja
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_95]
text=Crandor
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_96]
text=Entrana
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_97]
text=Draynor<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_98]
text=Jail
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_99]
text=Market
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_100]
text=Draynor Manor
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_101]
text=Barbarian<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_102]
text=Desert Mining<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_103]
text=Bedabin<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_104]
text=Exam Centre
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_105]
text=Digsite
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_106]
text=Lumber Yard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_107]
text=Palace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_108]
text=Cooks'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_109]
text=Monastery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_110]
text=Dwarven<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_111]
text=Ice<br>Mountain
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_112]
text=Black Knights'<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_113]
text=Goblin<br>Village
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_114]
text=White Knights'<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_115]
text=Park
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_116]
text=Kingdom of<br>Asgarnia
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_117]
text=Dark Wizards'<br>Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_118]
text=Slayer<br>Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_119]
text=Melzar's<br>Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_120]
text=Rimmington
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_121]
text=Wizards' Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_122]
text=Lumbridge<br>Swamp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_123]
text=Fishing<br>Platform
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_124]
text=Tai Bwo Wannai
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_125]
text=Shilo Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_126]
text=Shipyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_127]
text=Cairn Isle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_128]
text=Kharazi Jungle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_129]
text=Chaos<br>Temple
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_130]
text=Graveyard of<br>Shadows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_131]
text=Bandit<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_132]
text=Dark Warriors'<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_133]
text=Ruins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_134]
text=The Forgotten<br>Cemetery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_135]
text=Red Dragon<br>Isle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_136]
text=Wilderness
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_137]
text=Lava Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_138]
text=Frozen Waste<br>Plateau
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_139]
text=Agility Training<br>Area
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_140]
text=Pirates'<br>Hideout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_141]
text=Mage Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_142]
text=Deserted<br>Keep
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_143]
text=Scorpion<br>Pit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_144]
text=Rogues' Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_145]
text=Demonic<br>Ruins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_146]
text=Heroes'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_147]
text=Druids'<br>Circle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_148]
text=Taverley
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_149]
text=White Wolf<br>Mountain
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_150]
text=Catherby
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_151]
text=Camelot<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_152]
text=Seers'<br>Village
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_153]
text=Sinclair Mansion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_154]
text=Flax
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_155]
text=Beehives
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_156]
text=Sorcerer's Tower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_157]
text=Keep<br>Le Faye
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_158]
text=Legends'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_159]
text=Hemenster
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_160]
text=McGrubor's<br>Wood
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_161]
text=Coal<br>Trucks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_162]
text=Fishing<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_163]
text=Kingdom of<br>Kandarin
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_164]
text=East<br>Ardougne
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_165]
text=West<br>Ardougne
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_166]
text=Ardougne<br>Sewers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_167]
text=Combat<br>Training<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_168]
text=Tree Gnome<br>Stronghold
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_169]
text=Grand Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_170]
text=Swamp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_171]
text=Gnome Ball<br>Field
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_172]
text=Barbarian<br>Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_173]
text=Underground<br>Pass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_174]
text=Battlefield
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_175]
text=Baxtorian<br>Falls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_176]
text=Tree Gnome<br>Village
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_177]
text=Fight<br>Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_178]
text=Port<br>Khazard
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_179]
text=Yanille
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_180]
text=Wizards'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_181]
text=Observatory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_182]
text=Necromancer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_183]
text=Gu'Tanoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_184]
text=Feldip<br>Hills
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_185]
text=Ardougne<br>Zoo
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_186]
text=Morytania
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_187]
text=Mort Myre<br>Swamp
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_188]
text=Canifis
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_189]
text=River<br>Salve
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_190]
text=River Lum
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_191]
text=Temple
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_192]
text=Agility<br>Arena
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_193]
text=Burthorpe
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_194]
text=Death<br>Plateau
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_195]
text=Tirannwn
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_196]
text=Isafdar
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_197]
text=Arandar
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_198]
text=Prifddinas
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_199]
text=Tyras<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_200]
text=Elf<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_201]
text=Trollheim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_202]
text=Troll<br>Stronghold
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_203]
text=Mort'ton
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_204]
text=The<br>Hollows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_205]
text=Poison Waste
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_206]
text=Castle Wars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_207]
text=Champions'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_208]
text=Rellekka
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_209]
text=Golden<br>Apple Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_210]
text=Lighthouse
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_211]
text=Fremennik<br>Province
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_212]
text=Crafting<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_213]
text=Haunted<br>Woods
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_214]
text=Miscellania
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_215]
text=Etceteria
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_216]
text=Ape Atoll
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_217]
text=Crash<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_218]
text=Marim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_219]
text=Fenkenstrain's<br>Castle
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_220]
text=Mausoleum
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_221]
text=Trollweiss<br>Mountain
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_222]
text=Abandoned<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_223]
text=Ruins of<br>Uzer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_224]
text=River<br>Elid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_225]
sprite="mapfunction_sep,96"
category=category_1240
mapfunction=yes
show=both

[mapelement_226]
text=Pollnivneach
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_227]
text=Pyramid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_228]
text=Menaphos
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_229]
text=Sophanem
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_230]
text=Agility<br>Pyramid
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_231]
text=Graveyard
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_232]
text=Port<br>Phasmatys
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_233]
text=Ectofuntus
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_234]
text=Mountain<br>Camp
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_235]
text=Kharidian<br>Desert
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_236]
text=Ice Path
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_237]
text=Barrows
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_238]
text=Jiggig
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_239]
text=Mudskipper<br>Point
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_240]
text=Nardah
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_241]
text=Mage<br>Training<br>Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_242]
text=Keldagrim<br>Entrance
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_243]
text=Waterbirth<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_244]
text=Lletya
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_245]
text=Burgh de Rott
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_246]
text=Lizards
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_247]
text=Quarry
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_248]
text=Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_249]
text=Mos Le'Harmless
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_250]
text=Distilleries
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_251]
text=Ranging<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_252]
text=Dragontooth<br>Island
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_253]
text=Piscatoris<br>Fishing<br>Colony
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_254]
text=Here Be<br>Penguins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_255]
text=Void Knights'<br>Outpost
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_256]
text=Lunar Isle
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_257]
text=Pirates' Cove
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_258]
text=Vultures
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_259]
text=Port<br>Tyras
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_260]
text=Castle<br>Drakan
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_261]
text=Sanguinesti<br>Region
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_262]
text=Meiyerditch
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_263]
text=Witchaven
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_264]
text=Warriors'<br>Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_265]
text=Musa Point
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_266]
text=Eagles'<br>Peak
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_267]
text=Falconer
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_268]
text=Barbarian<br>Assault
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_269]
text=Iceberg
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_270]
text=Pest<br>Control
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_271]
text=Neitiznot
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_272]
text=Jatizso
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_273]
text=Fremennik Isles
textsize=2
textcolour=0xf09040
mapfunction=yes
category=category_950

[mapelement_274]
text=Tower of<br>Life
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_275]
text=Clocktower
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_276]
text=Harmony
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_277]
text=Trawler
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_278]
text=Otto's<br>Grotto
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_279]
text=Party Room
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_280]
text=Courthouse
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_281]
text=God Wars<br>Dungeon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_282]
text=Wilderness<br>Volcano
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_283]
text=Clan Wars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_284]
text=Grand Exchange
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_285]
text=Oo'glog
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_286]
text=Fist of Guthix
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_287]
text=Stealing Creation
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_288]
text=Soul Wars
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_289]
text=Queen's<br>Chamber
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_290]
text=Soldiers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_291]
text=Guardians
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_292]
text=Ice Queen's<br>Lair
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_293]
text=Fountain<br>of Heroes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_294]
text=Mountain<br>dwarves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_295]
text=Nora T. Hagg's<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_296]
text=Salarin the<br>Twisted
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_297]
text=H.A.M. Cult
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_298]
text=Draynor Sewers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_299]
text=Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_300]
text=Watermill<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_301]
text=Champions'<br>Challenge
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_302]
text=Draynor Manor<br>basement
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_303]
text=VTAM Corporation
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_304]
text=Bank vault
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_305]
text=Goblin Maze
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_306]
text=Chasm of<br>Tears
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_307]
text=Tears of<br>Guthix
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_308]
text=Lumbridge<br>Castle<br>cellar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_309]
text=Giant frogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_310]
text=Hill giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_311]
text=Chronozon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_312]
text=Here be<br>dead stuff
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_313]
text=Thugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_314]
text=Dave's<br>Basement<br>of Doom
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_315]
text=Poison spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_316]
text=Poison<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_317]
text=Zombies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_318]
text=Zombies & rocks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_319]
text=Skeletons<br>& zombies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_320]
text=Earth warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_321]
text=Earth<br>warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_322]
text=Skeletons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_323]
text=Black demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_324]
text=Black<br>demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_325]
text=Chaos<br>druids
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_326]
text=Hobgoblins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_327]
text=Red spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_328]
text=Red<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_329]
text=Rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_330]
text=Banshees
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_331]
text=Kurask
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_332]
text=Cave crawlers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_333]
text=Turoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_334]
text=Basilisks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_335]
text=Aberrant<br>spectres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_336]
text=Rock<br>slugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_337]
text=Cockatrice
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_338]
text=Pyrefiends
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_339]
text=Jellies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_340]
text=Throne room
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_341]
text=Beware of the<br>mushrooms
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_342]
text=Shrine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_343]
text=Otherworldly<br>beings
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_344]
text=Puro-puro
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_345]
text=Moss giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_346]
text=Moss<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_347]
text=Dogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_348]
text=Fire<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_349]
text=Red dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_350]
text=Bronze<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_351]
text=Iron & steel<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_352]
text=Greater demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_353]
text=Agility Arena
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_354]
text=Jogres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_355]
text=Elvarg
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_356]
text=Lesser demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_357]
text=Gift of<br>Peace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_358]
text=Grain of<br>Plenty
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_359]
text=Box of<br>Health
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_360]
text=Cradle of<br>Life
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_361]
text=Crypt<br>rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_362]
text=Dungeon<br>rats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_363]
text=Nechryael
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_364]
text=Dagannoth
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_365]
text=Infernal<br>magi
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_366]
text=Dragons & fire<br>elementals
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_367]
text=Dust<br>devils
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_368]
text=Waterfiends
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_369]
text=Rock<br>crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_370]
text=Ice<br>giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_371]
text=Zamorak<br>fighters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_372]
text=Cave<br>bugs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_373]
text=Shadow<br>hounds &<br>wolves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_374]
text=Dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_375]
text=Giant<br>ants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_376]
text=Spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_377]
text=Shadow<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_378]
text=Crypt & shadow<br>spiders
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_379]
text=Leeches
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_380]
text=Ice warriors<br>& giants
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_381]
text=Gargoyles
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_382]
text=Trolls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_383]
text=Ice trolls
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_384]
text=Monks of<br>Zamorak
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_385]
text=Mummies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_386]
text=Zombies,<br>skeletons &<br>animated<br>items
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_387]
text=Fight Pit
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_388]
text=Fight Cave
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_389]
text=Library
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_390]
text=Terror dogs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_391]
text=Anger
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_392]
text=Hopelessness
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_393]
text=Confusion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_394]
text=Fear
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_395]
text=Saradomin's<br>Encampment
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_396]
text=Zamorak's<br>Fortress
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_397]
text=Armadyl's<br>Eyrie
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_398]
text=Bandos's<br>Stronghold
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_399]
text=Distillery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_400]
text=Dead people
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_401]
text=Nothing<br>interesting<br>happens<br>here
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_402]
text=Beware of<br>the scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_403]
text=Mining Guild
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_404]
text=Access to<br>Falador
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_405]
text=Hammerspike's<br>hangout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_406]
text=Pickaxe<br>factory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_407]
text=Boot
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_408]
text=River Kelda
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_409]
text=Dondakan's<br>rock
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_410]
text=Minecarts
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_411]
text=Blast<br>Furnace
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_412]
text=Brewery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_413]
text=Agility course
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_414]
text=Wire<br>machine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_415]
text=Bone<br>collector
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_416]
text=Oldak's<br>teleportation<br>laboratory
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_417]
text=Station
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_418]
text=Council<br>chamber
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_419]
text=Ur-tag
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_420]
text=Ur-meg
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_421]
text=Ur-zek & Ur-taal
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_422]
text=Tegdak
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_423]
text=Ur-vass
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_424]
text=Nursery
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_425]
text=Cauldron of<br>Thunder
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_426]
text=Black Knights'<br>Base
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_427]
text=Hellhounds
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_428]
text=Fire Obelisk
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_429]
text=Black dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_430]
text=Black<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_431]
text=Dramen Tree
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_432]
text=Animated<br>axes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_433]
text=Chaos<br>dwarves
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_434]
text=Blue<br>dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_435]
text=Poisonous<br>scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_436]
text=Agility<br>course<br>spikes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_437]
text=Mage Arena<br>bank
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_438]
text=King<br>Black<br>Dragon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_439]
text=Shadow<br>warriors
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_440]
text=Pit scorpions
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_441]
text=Rat Pits
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_442]
text=Bats
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_443]
text=Ogres
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_444]
text=Here be<br>goblins
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_445]
text=Skeletal wyverns
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_446]
text=Pirates
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_447]
text=Muggers
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_448]
text=Black<br>Guard<br>H.Q.
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_449]
text=Zanik's<br>bedroom
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_450]
text=Essence<br>Mine
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_451]
text=Miscellania<br>Expansion
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_452]
text=Sea snakes
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_453]
text=Altar
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_454]
text=Lizards &<br>Zamorak fighters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_455]
text=Goutweed<br>store
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_456]
text=Troll<br>generals
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_457]
text=Kitchen
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_458]
text=Tanglefeet
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_459]
text=Giant rock crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_460]
text=Giant<br>rock crabs
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_461]
text=Rock lobsters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_462]
text=Rock<br>lobsters
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_463]
text=Wallasalki
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_464]
text=Dagannoth<br>Kings
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_465]
text=Volcano
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_466]
text=Cave horrors<br>&<br>albino bats
textsize=1
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_467]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_468]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_469]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_470]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_471]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_472]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_473]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_474]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_475]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_476]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_477]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_478]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_479]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_480]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_481]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_482]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_483]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_484]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_485]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_486]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_487]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_488]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_489]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_490]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_491]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_492]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_493]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_494]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_495]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_496]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_497]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_498]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_499]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_500]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_501]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_502]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_503]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_504]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_505]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_506]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_507]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_508]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_509]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_510]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_511]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_512]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_513]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_514]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_515]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_516]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_517]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_518]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_519]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_520]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_521]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_522]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_523]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_524]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_525]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_526]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_527]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_528]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_529]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_530]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_531]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_532]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_533]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_534]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_535]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_536]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_537]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_538]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_539]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_540]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_541]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_542]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_543]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_544]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_545]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_546]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_547]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_548]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_549]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_550]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_551]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_552]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_553]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_554]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_555]
sprite="mapfunction_sep,0"
category=category_951
mapfunction=yes
show=both

[mapelement_556]
sprite="mapfunction_sep,1"
category=category_952
mapfunction=yes
show=both

[mapelement_557]
sprite="mapfunction_sep,2"
category=category_953
mapfunction=yes
show=both

[mapelement_558]
sprite="mapfunction_sep,3"
category=category_954
mapfunction=yes
show=both

[mapelement_559]
sprite="mapfunction_sep,4"
category=category_955
mapfunction=yes
show=both

[mapelement_560]
sprite="mapfunction_sep,5"
category=category_1156
mapfunction=yes
show=both

[mapelement_561]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both

[mapelement_562]
sprite="mapfunction_sep,7"
category=category_1158
mapfunction=yes
show=both

[mapelement_563]
sprite="mapfunction_sep,8"
category=category_1159
mapfunction=yes
show=both

[mapelement_564]
sprite="mapfunction_sep,9"
category=category_1160
mapfunction=yes
show=both

[mapelement_565]
sprite="mapfunction_sep,10"
category=category_1161
mapfunction=yes
show=both

[mapelement_566]
sprite="mapfunction_sep,11"
category=category_1162
mapfunction=yes
show=both

[mapelement_567]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=both

[mapelement_568]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=minimap

[mapelement_569]
sprite="mapfunction_sep,13"
category=category_1163
mapfunction=yes
show=both

[mapelement_570]
sprite="mapfunction_sep,14"
category=category_1164
mapfunction=yes
show=both

[mapelement_571]
sprite="mapfunction_sep,15"
category=category_1165
mapfunction=yes
show=both

[mapelement_572]
sprite="mapfunction_sep,16"
category=category_1166
mapfunction=yes
show=both

[mapelement_573]
sprite="mapfunction_sep,17"
category=category_1167
mapfunction=yes
show=both

[mapelement_574]
sprite="mapfunction_sep,18"
category=category_1168
mapfunction=yes
show=both

[mapelement_575]
sprite="mapfunction_sep,19"
category=category_1169
mapfunction=yes
show=both

[mapelement_576]
sprite="mapfunction_sep,20"
category=category_1170
mapfunction=yes
show=both

[mapelement_577]
sprite="mapfunction_sep,21"
category=category_1171
mapfunction=yes
show=both

[mapelement_578]
sprite="mapfunction_sep,22"
category=category_1172
mapfunction=yes
show=both

[mapelement_579]
sprite="mapfunction_sep,23"
category=category_1173
mapfunction=yes
show=both

[mapelement_580]
sprite="mapfunction_sep,24"
category=category_1174
mapfunction=yes
show=both

[mapelement_581]
sprite="mapfunction_sep,25"
category=category_1175
mapfunction=yes
show=both

[mapelement_582]
sprite="mapfunction_sep,26"
category=category_1176
mapfunction=yes
show=both

[mapelement_583]
sprite="mapfunction_sep,27"
category=category_1177
mapfunction=yes
show=both

[mapelement_584]
sprite="mapfunction_sep,28"
category=category_1178
mapfunction=yes
show=both

[mapelement_585]
sprite="mapfunction_sep,29"
category=category_1179
mapfunction=yes
show=both

[mapelement_586]
sprite="mapfunction_sep,30"
category=category_1180
mapfunction=yes
show=both

[mapelement_587]
sprite="mapfunction_sep,31"
category=category_1181
mapfunction=yes
show=both

[mapelement_588]
sprite="mapfunction_sep,32"
category=category_1182
mapfunction=yes
show=both

[mapelement_589]
sprite="mapfunction_sep,33"
category=category_1183
mapfunction=yes
show=both

[mapelement_590]
sprite="mapfunction_sep,34"
category=category_1184
mapfunction=yes
show=both

[mapelement_591]
sprite="mapfunction_sep,35"
category=category_1185
mapfunction=yes
show=both

[mapelement_592]
sprite="mapfunction_sep,36"
category=category_1186
mapfunction=yes
show=both

[mapelement_593]
sprite="mapfunction_sep,37"
category=category_1187
mapfunction=yes
show=both

[mapelement_594]
sprite="mapfunction_sep,38"
category=category_1188
mapfunction=yes
show=both

[mapelement_595]
sprite="mapfunction_sep,39"
category=category_1189
mapfunction=yes
show=both

[mapelement_596]
sprite="mapfunction_sep,40"
category=category_1190
mapfunction=yes
show=both

[mapelement_597]
sprite="mapfunction_sep,41"
category=category_1191
mapfunction=yes
show=both

[mapelement_598]
sprite="mapfunction_sep,42"
category=category_1192
mapfunction=yes
show=both

[mapelement_599]
sprite="mapfunction_sep,43"
category=category_1193
mapfunction=yes
show=both

[mapelement_600]
sprite="mapfunction_sep,44"
category=category_1194
mapfunction=yes
show=both

[mapelement_601]
sprite="mapfunction_sep,45"
category=category_1195
mapfunction=yes
show=both

[mapelement_602]
sprite="mapfunction_sep,46"
category=category_1196
mapfunction=yes
show=both

[mapelement_603]
sprite="mapfunction_sep,47"
category=category_1197
mapfunction=yes
show=both

[mapelement_604]
sprite="mapfunction_sep,48"
category=category_1198
mapfunction=yes
show=both

[mapelement_605]
sprite="mapfunction_sep,49"
category=category_1199
mapfunction=yes
show=both

[mapelement_606]
sprite="mapfunction_sep,50"
category=category_1200
mapfunction=yes
show=both

[mapelement_607]
sprite="mapfunction_sep,51"
category=category_1201
mapfunction=yes
show=both

[mapelement_608]
sprite="mapfunction_sep,52"
category=category_1202
mapfunction=yes
show=both

[mapelement_609]
sprite="mapfunction_sep,54"
category=category_1203
mapfunction=yes
show=both

[mapelement_610]
sprite="mapfunction_sep,55"
category=category_1204
mapfunction=yes
show=both

[mapelement_611]
sprite="mapfunction_sep,53"
category=category_1205
mapfunction=yes
show=both

[mapelement_612]
sprite="mapfunction_sep,56"
category=category_1206
mapfunction=yes
show=both

[mapelement_613]
sprite="mapfunction_sep,58"
category=category_1207
mapfunction=yes
show=both

[mapelement_614]
sprite="mapfunction_sep,59"
category=category_1208
mapfunction=yes
show=both

[mapelement_615]
sprite="mapfunction_sep,60"
category=category_1209
mapfunction=yes
show=both

[mapelement_616]
sprite="mapfunction_sep,61"
category=category_1210
mapfunction=yes
show=both

[mapelement_617]
sprite="mapfunction_sep,62"
mapfunction=yes
show=both

[mapelement_618]
sprite="mapfunction_sep,63"
category=category_1211
mapfunction=yes
show=both

[mapelement_619]
sprite="mapfunction_sep,65"
category=category_1212
mapfunction=yes
show=both

[mapelement_620]
sprite="mapfunction_sep,55"
category=category_1213
mapfunction=yes
show=both

[mapelement_621]
sprite="mapfunction_sep,57"
category=category_1214
mapfunction=yes
show=both

[mapelement_622]
sprite="mapfunction_sep,67"
category=category_1215
mapfunction=yes
show=both

[mapelement_623]
sprite="mapfunction_sep,68"
category=category_1216
mapfunction=yes
show=both

[mapelement_624]
sprite="mapfunction_sep,69"
mapfunction=yes
show=both

[mapelement_625]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_626]
sprite="mapfunction_sep,71"
category=category_1218
mapfunction=yes
show=both

[mapelement_627]
sprite="mapfunction_sep,72"
category=category_1219
mapfunction=yes
show=both

[mapelement_628]
sprite="mapfunction_sep,73"
category=category_1220
mapfunction=yes
show=both

[mapelement_629]
sprite="mapfunction_sep,74"
category=category_1221
mapfunction=yes
show=both

[mapelement_630]
sprite="mapfunction_sep,75"
category=category_1260
mapfunction=yes
show=both

[mapelement_631]
sprite="mapfunction_sep,76"
category=category_1222
mapfunction=yes
show=both

[mapelement_632]
sprite="mapfunction_sep,93"
category=category_1223
mapfunction=yes
show=both

[mapelement_633]
sprite="mapfunction_sep,77"
category=category_1224
mapfunction=yes
show=both

[mapelement_634]
sprite="mapfunction_sep,92"
category=category_1225
mapfunction=yes
show=both

[mapelement_635]
sprite="mapfunction_sep,94"
category=category_1226
mapfunction=yes
show=both

[mapelement_636]
sprite="mapfunction_sep,95"
category=category_1227
mapfunction=yes
show=both

[mapelement_637]
sprite="mapfunction_sep,78"
category=category_1228
mapfunction=yes
show=both

[mapelement_638]
sprite="mapfunction_sep,79"
mapfunction=yes
show=both

[mapelement_639]
sprite="mapfunction_sep,80"
mapfunction=yes
show=both

[mapelement_640]
sprite="mapfunction_sep,81"
mapfunction=yes
show=both

[mapelement_641]
sprite="mapfunction_sep,82"
mapfunction=yes
show=both

[mapelement_642]
sprite="mapfunction_sep,83"
mapfunction=yes
show=both

[mapelement_643]
sprite="mapfunction_sep,84"
mapfunction=yes
show=both

[mapelement_644]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_180,0,7

[mapelement_645]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_180,7,9999

[mapelement_646]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1850,0,5

[mapelement_647]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1850,5,9999

[mapelement_648]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_961,0,60

[mapelement_649]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_961,60,9999

[mapelement_650]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5331,0,35

[mapelement_651]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5331,35,9999

[mapelement_652]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5032,0,63

[mapelement_653]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5032,63,9999

[mapelement_654]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_148,0,11

[mapelement_655]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_148,11,9999

[mapelement_656]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3523,0,150

[mapelement_657]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3523,150,9999

[mapelement_658]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5733,0,60

[mapelement_659]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5733,60,9999

[mapelement_660]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_147,0,6

[mapelement_661]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_147,6,9999

[mapelement_662]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1404,0,127

[mapelement_663]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1404,127,9999

[mapelement_664]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5133,0,90

[mapelement_665]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5133,90,9999

[mapelement_666]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2326,0,90

[mapelement_667]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2326,90,9999

[mapelement_668]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1803,0,90

[mapelement_669]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1803,90,9999

[mapelement_670]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3550,0,11

[mapelement_671]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3550,11,9999

[mapelement_672]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_4105,0,18

[mapelement_673]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_4105,18,9999

[mapelement_674]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_451,0,2

[mapelement_675]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_451,2,9999

[mapelement_676]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1372,0,125

[mapelement_677]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1372,125,9999

[mapelement_678]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_532,0,11

[mapelement_679]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_532,11,9999

[mapelement_680]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2258,0,13

[mapelement_681]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2258,13,9999

[mapelement_682]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1938,0,110

[mapelement_683]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1938,110,9999

[mapelement_684]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_4684,0,150

[mapelement_685]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_4684,150,9999

[mapelement_686]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_1051,0,10

[mapelement_687]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_1051,10,9999

[mapelement_688]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_3185,0,240

[mapelement_689]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_3185,240,9999

[mapelement_690]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_334,0,28

[mapelement_691]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_334,28,9999

[mapelement_692]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_657,0,2

[mapelement_693]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_657,2,9999

[mapelement_694]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_2610,0,14

[mapelement_695]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_2610,14,9999

[mapelement_696]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayerbit_5387,0,250

[mapelement_697]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayerbit_5387,250,9999

[mapelement_698]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=both
condition=varplayer_302,0,61

[mapelement_699]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both
condition=varplayer_302,60,9999

[mapelement_700]
sprite="mapfunction_sep,97"
category=category_1229
mapfunction=yes
show=both

[mapelement_701]
text=Kalphite<br>Hive
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_702]
text=Mobilising<br>Armies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_703]
sprite="mapfunction_sep,99"
mapfunction=yes
show=both

[mapelement_704]
sprite="mapfunction_sep,100"
mapfunction=yes
show=both

[mapelement_705]
sprite="mapfunction_sep,101"
mapfunction=yes
show=both

[mapelement_706]
sprite="mapfunction_sep,102"
mapfunction=yes
show=both

[mapelement_707]
sprite="mapfunction_sep,103"
category=category_1270
mapfunction=yes
show=both

[mapelement_708]
text=Aquanites
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_709]
sprite="mapdots_interface,1"
mapfunction=no
show=minimap

[mapelement_710]
text=Rogues'<br>Den
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_711]
text=Bag of<br>supplies
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_712]
text=Pillars
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_713]
text=Sleeping<br>dragon
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_714]
text=Damaged<br>wall
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_715]
text=Rocks
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_716]
text=Roots
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_717]
text=Roddeck's<br>hideout
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_718]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_719]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_720]
text=Living<br>rock caverns
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_721]
sprite="mapfunction_sep,98"
category=category_1369
mapfunction=yes
show=both

[mapelement_722]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes
show=minimap

[mapelement_723]
sprite="mapfunction_sep,6"
category=category_1157
mapfunction=yes

[mapelement_724]
sprite="dungeon_entrance_icon,0"
mouseovergraphic="dungeon_entrance_icon,2"
category=category_949
mapfunction=yes
op1=Open
show=both
opbase=Map

[mapelement_725]
sprite="dungeon_entrance_icon,1"
mouseovergraphic="dungeon_entrance_icon,3"
category=category_948
mapfunction=yes
op1=Open
opbase=Map

[mapelement_726]
text=Ancient cavern
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_727]
text=Mithril dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_728]
text=Hellhounds
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_729]
text=Greater demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_730]
text=Blue dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_731]
text=Gargoyles
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_732]
text=Abyssal demons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_733]
text=Dark beasts
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_734]
text=Iron dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_735]
text=Steel dragons
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_736]
sprite="mapfunction_sep,12"
category=category_949
mapfunction=yes
show=both
condition=varplayerbit_6884,2,2

[mapelement_737]
mapfunction=no
show=both
condition=varplayerbit_6913,5,5
condition2=varplayer_32,1,2
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_738]
mapfunction=no
show=both
condition=varplayerbit_6913,5,5
condition2=varplayer_32,1,2
polygonpoint0=15,13
polygonpoint1=15,44
polygonpoint2=50,44
polygonpoint3=50,13
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_739]
mapfunction=no
show=both
condition=varplayerbit_6913,13,13
condition2=varplayer_63,1,2
polygonpoint0=18,5
polygonpoint1=18,45
polygonpoint2=55,45
polygonpoint3=55,5
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_740]
mapfunction=no
show=both
condition=varplayerbit_6913,13,13
condition2=varplayer_63,3,4
polygonpoint0=0,-15
polygonpoint1=0,50
polygonpoint2=65,50
polygonpoint3=65,-15
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_741]
mapfunction=no
show=both
condition=varplayerbit_6913,13,13
condition2=varplayer_63,5,5
polygonpoint0=18,5
polygonpoint1=18,45
polygonpoint2=55,45
polygonpoint3=55,5
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_742]
mapfunction=no
show=both
condition=varplayerbit_6913,11,11
condition2=varplayer_107,1,4
polygonpoint0=34,-8
polygonpoint1=34,10
polygonpoint2=40,20
polygonpoint3=55,20
polygonpoint4=55,-13
polygonpoint5=35,-60
polygonpoint6=0,-60
polygonpoint7=0,-45
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_743]
mapfunction=no
show=both
condition=varplayerbit_6913,1,1
condition2=varplayer_29,1,1
polygonpoint0=-3,0
polygonpoint1=-3,57
polygonpoint2=-15,57
polygonpoint3=-50,92
polygonpoint4=-50,115
polygonpoint5=40,103
polygonpoint6=55,82
polygonpoint7=65,82
polygonpoint8=65,25
polygonpoint9=40,25
polygonpoint10=32,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_744]
text=Mill
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

[mapelement_745]
text=Chickens
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

[mapelement_746]
text=Chickens
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

[mapelement_747]
text=Cows
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

[mapelement_748]
text=Goblins
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

[mapelement_749]
text=Sheep
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

[mapelement_750]
text=Castle
textsize=0
textcolour=0xff0000
mapfunction=yes
category=category_950
show=both
condition=varplayer_29,1,1

[mapelement_751]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,1,39
polygonpoint0=0,0
polygonpoint1=0,11
polygonpoint2=10,11
polygonpoint3=10,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_752]
text=Start of<br>Black Knights' Fortress
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_130,0,0
condition2=varplayerbit_697,159,159

[mapelement_753]
text=Start of<br>Cook's Assistant
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_29,0,0
condition2=varplayerbit_697,1,1

[mapelement_754]
text=Start of<br>Demon Slayer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2561,0,0
condition2=varplayerbit_697,2,2

[mapelement_755]
text=Start of<br>Doric's Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_31,0,0
condition2=varplayerbit_697,3,3

[mapelement_756]
text=Start of<br>Dragon Slayer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_176,0,0
condition2=varplayerbit_697,4,4

[mapelement_757]
text=Start of<br>Ernest the Chicken
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_32,0,0
condition2=varplayerbit_697,5,5

[mapelement_758]
text=Start of<br>Goblin Diplomacy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2378,0,0
condition2=varplayerbit_697,6,6

[mapelement_759]
text=Start of<br>Imp Catcher
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_160,0,0
condition2=varplayerbit_697,7,7

[mapelement_760]
text=Start of<br>The Knight's Sword
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_122,0,0
condition2=varplayerbit_697,8,8

[mapelement_761]
text=Start of<br>Pirate's Treasure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_71,0,0
condition2=varplayerbit_697,9,9

[mapelement_762]
text=Start of<br>Prince Ali Rescue
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_273,0,0
condition2=varplayerbit_697,10,10

[mapelement_763]
text=Start of<br>The Restless Ghost
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_107,0,0
condition2=varplayerbit_697,11,11

[mapelement_764]
text=Start of<br>Romeo & Juliet
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_144,0,0
condition2=varplayerbit_697,12,12

[mapelement_765]
text=Start of<br>Rune Mysteries
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_63,0,0
condition2=varplayerbit_697,13,13

[mapelement_766]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,40,54
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=11,8
polygonpoint3=11,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_767]
text=Start of<br>Vampire Slayer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
op1=Scroll
condition=varplayer_178,0,0
condition2=varplayerbit_697,16,16
opbase=Start of Vampire Slayer

[mapelement_768]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,125,149
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=11,8
polygonpoint3=11,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_769]
text=Start of<br>Animal Magnetism
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3185,0,0
condition2=varplayerbit_697,18,18

[mapelement_770]
text=Start of<br>Between a Rock...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_299,0,0
condition2=varplayerbit_697,19,19

[mapelement_771]
text=Route to<br>Between a Rock...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_299,0,0
condition2=varplayerbit_697,19,19

[mapelement_772]
text=Start of<br>Big Chompy Bird Hunting
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_293,0,0
condition2=varplayerbit_697,20,20

[mapelement_773]
text=Start of<br>Biohazard
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_68,0,0
condition2=varplayerbit_697,21,21

[mapelement_774]
text=Start of<br>Cabin Fever
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_655,0,0
condition2=varplayerbit_697,22,22

[mapelement_775]
text=Start of<br>Clock Tower
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_10,0,0
condition2=varplayerbit_697,23,23

[mapelement_776]
text=Start of<br>Contact!
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3274,0,0
condition2=varplayerbit_697,24,24

[mapelement_777]
text=Start of<br>Zogre Flesh Eaters
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_487,0,0
condition2=varplayerbit_697,25,25

[mapelement_778]
text=Start of<br>Darkness of Hallowvale
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2573,0,0
condition2=varplayerbit_697,27,27

[mapelement_779]
text=Start of<br>Death to the Dorgeshuun
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
textbackgroundfill=0x2095c8ff
op1=Scroll
condition=varplayerbit_2258,0,0
condition2=varplayerbit_697,28,28
opbase=Start of Death to the Dorgeshuun

[mapelement_780]
text=Route to<br>Death to the Dorgeshuun
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
textbackgroundfill=0x2095c8ff
op1=Scroll
op2=Follow
condition=varplayerbit_2258,0,0
condition2=varplayerbit_697,28,28
opbase=Route to Death to the Dorgeshuun

[mapelement_781]
text=Start of<br>Death Plateau
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_314,0,0
condition2=varplayerbit_697,29,29

[mapelement_782]
text=Start of<br>Desert Treasure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_358,0,0
condition2=varplayerbit_697,30,30

[mapelement_783]
text=Start of<br>Devious Minds
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1465,0,0
condition2=varplayerbit_697,31,31

[mapelement_784]
text=Start of<br>The Dig Site
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_131,0,0
condition2=varplayerbit_697,32,32

[mapelement_785]
text=Start of<br>Druidic Ritual
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_80,0,0
condition2=varplayerbit_697,33,33

[mapelement_786]
text=Start of<br>Dwarf Cannon
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_0,0,0
condition2=varplayerbit_697,34,34

[mapelement_787]
text=Start of<br>Eadgar's Ruse
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_335,0,0
condition2=varplayerbit_697,35,35

[mapelement_788]
text=Start of<br>Eagles' Peak
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2780,0,0
condition2=varplayerbit_697,36,36

[mapelement_789]
text=Start of<br>Elemental Workshop II
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2639,0,0
condition2=varplayerbit_697,38,38

[mapelement_790]
text=Start of<br>Enakhra's Lament
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1560,0,0
condition2=varplayerbit_697,39,39

[mapelement_791]
text=Start of<br>Enlightened Journey
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2866,0,0
condition2=varplayerbit_697,40,40

[mapelement_792]
text=Start of<br>The Eyes of Glouphrie
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2497,0,0
condition2=varplayerbit_697,41,41

[mapelement_793]
text=Start of<br>Fairytale I - Growing Pains
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1803,0,0
condition2=varplayerbit_697,42,42

[mapelement_794]
text=Start of<br>Fairytale II - Cure a Queen
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2326,0,0
condition2=varplayerbit_697,43,43

[mapelement_795]
text=Start of<br>Family Crest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_148,0,0
condition2=varplayerbit_697,44,44

[mapelement_796]
text=Start of<br>The Feud
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_334,0,0
condition2=varplayerbit_697,45,45

[mapelement_797]
text=Start of<br>Fight Arena
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_17,0,0
condition2=varplayerbit_697,46,46

[mapelement_798]
text=Start of<br>Fishing Contest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_11,0,0
condition2=varplayerbit_697,47,47

[mapelement_799]
text=Start of<br>Forgettable Tale...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_822,0,0
condition2=varplayerbit_697,48,48

[mapelement_800]
text=Route to<br>Forgettable Tale...
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_822,0,0
condition2=varplayerbit_697,48,48

[mapelement_801]
text=Start of<br>The Fremennik Trials
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_347,0,0
condition2=varplayerbit_697,49,49

[mapelement_802]
text=Start of<br>Waterfall Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_65,0,0
condition2=varplayerbit_697,50,50

[mapelement_803]
text=Start of<br>Garden of Tranquillity
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_961,0,0
condition2=varplayerbit_697,51,51

[mapelement_804]
text=Start of<br>Gertrude's Cat
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_180,0,0
condition2=varplayerbit_697,52,52

[mapelement_805]
text=Start of<br>Ghosts Ahoy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_217,0,0
condition2=varplayerbit_697,53,53

[mapelement_806]
text=Start of<br>The Giant Dwarf
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_571,0,0
condition2=varplayerbit_697,54,54

[mapelement_807]
text=Route of<br>The Giant Dwarf
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_571,0,0
condition2=varplayerbit_697,54,54

[mapelement_808]
text=Start of<br>The Golem
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_346,0,0
condition2=varplayerbit_697,55,55

[mapelement_809]
text=Start of<br>The Grand Tree
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_150,0,0
condition2=varplayerbit_697,56,56

[mapelement_810]
text=Start of<br>The Hand in the Sand
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1527,0,0
condition2=varplayerbit_697,57,57

[mapelement_811]
text=Start of<br>Haunted Mine
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_382,0,0
condition2=varplayerbit_697,58,58

[mapelement_812]
text=Start of<br>Hazeel Cult
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_223,0,0
condition2=varplayerbit_697,59,59

[mapelement_813]
text=Start of<br>Heroes' Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_188,0,0
condition2=varplayerbit_697,60,60

[mapelement_814]
text=Start of<br>Holy Grail
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_5,0,0
condition2=varplayerbit_697,61,61

[mapelement_815]
text=Start of<br>Horror from the Deep
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_34,0,0
condition2=varplayerbit_697,62,62

[mapelement_816]
text=Start of<br>Icthlarin's Little Helper
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_418,0,0
condition2=varplayerbit_697,63,63

[mapelement_817]
text=Start of<br>In Aid of the Myreque
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1990,0,0
condition2=varplayerbit_697,64,64

[mapelement_818]
text=Route to<br>In Aid of the Myreque
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1990,0,0
condition2=varplayerbit_697,64,64

[mapelement_819]
text=Start of<br>In Search of the Myreque
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_387,0,0
condition2=varplayerbit_697,65,65

[mapelement_820]
text=Start of<br>Jungle Potion
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_175,0,0
condition2=varplayerbit_697,66,66

[mapelement_821]
text=Start of<br>Legends' Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_139,0,0
condition2=varplayerbit_697,67,67

[mapelement_822]
text=Start of<br>Lost City
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_147,0,0
condition2=varplayerbit_697,68,68

[mapelement_823]
text=Start of<br>The Lost Tribe
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_532,0,0
condition2=varplayerbit_697,69,69

[mapelement_824]
text=Start of<br>Lunar Diplomacy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2448,0,0
condition2=varplayerbit_697,70,70

[mapelement_825]
text=Start of<br>Making History
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1383,0,0
condition2=varplayerbit_697,71,71

[mapelement_826]
text=Start of<br>Merlin's Crystal
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_14,0,0
condition2=varplayerbit_697,72,72

[mapelement_827]
text=Start of<br>Monkey Madness
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_365,0,0
condition2=varplayerbit_697,73,73

[mapelement_828]
text=Start of<br>Monk's Friend
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_30,0,0
condition2=varplayerbit_697,74,74

[mapelement_829]
text=Start of<br>Mountain Daughter
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_260,0,0
condition2=varplayerbit_697,75,75

[mapelement_830]
text=Start of<br>Mourning's Ends Part I
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_517,0,0
condition2=varplayerbit_697,76,76

[mapelement_831]
text=Start of<br>Mourning's Ends Part II
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1103,0,8
condition2=varplayerbit_697,77,77

[mapelement_832]
text=Start of<br>Within the Light
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6553,0,0
condition2=varplayerbit_697,161,161

[mapelement_833]
text=Start of<br>Murder Mystery
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_192,0,0
condition2=varplayerbit_697,78,78

[mapelement_834]
text=Start of<br>My Arm's Big Adventure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2790,0,0
condition2=varplayerbit_697,79,79

[mapelement_835]
text=Route to<br>My Arm's Big Adventure
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2790,0,0
condition2=varplayerbit_697,79,79

[mapelement_836]
text=Start of<br>Nature Spirit
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_307,0,0
condition2=varplayerbit_697,80,80

[mapelement_837]
text=Route to<br>Nature Spirit
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_307,0,0
condition2=varplayerbit_697,80,80

[mapelement_838]
text=Start of<br>Observatory Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_112,0,0
condition2=varplayerbit_697,81,81

[mapelement_839]
text=Start of<br>One Small Favour
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_416,0,0
condition2=varplayerbit_697,82,82

[mapelement_840]
text=Start of<br>Plague City
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_165,0,0
condition2=varplayerbit_697,83,83

[mapelement_841]
text=Start of<br>Priest in Peril
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_302,0,0
condition2=varplayerbit_697,84,84

[mapelement_842]
text=Start of<br>Rag and Bone Man
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_714,0,0
condition2=varplayerbit_697,85,85

[mapelement_843]
text=Start of<br>Ratcatchers
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1404,0,0
condition2=varplayerbit_697,86,86

[mapelement_844]
text=Start of<br>Recipe for Disaster
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1850,0,0
condition2=varplayerbit_697,87,87

[mapelement_845]
text=Start of<br>Recruitment Drive
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_657,0,0
condition2=varplayerbit_697,88,88

[mapelement_846]
text=Start of<br>Roving Elves
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_402,0,0
condition2=varplayerbit_697,90,90

[mapelement_847]
text=Start of<br>Royal Trouble
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2140,0,0
condition2=varplayerbit_697,91,91

[mapelement_848]
text=Start of<br>Rum Deal
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_600,0,0
condition2=varplayerbit_697,92,92

[mapelement_849]
text=Start of<br>Scorpion Catcher
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_76,0,0
condition2=varplayerbit_697,93,93

[mapelement_850]
text=Start of<br>Sea Slug
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_159,0,0
condition2=varplayerbit_697,94,94

[mapelement_851]
text=Start of<br>The Slug Menace
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2610,0,0
condition2=varplayerbit_697,95,95

[mapelement_852]
text=Start of<br>Shades of Mort'ton
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_339,0,0
condition2=varplayerbit_697,96,96

[mapelement_853]
text=Start of<br>Shadow of the Storm
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1372,0,0
condition2=varplayerbit_697,97,97

[mapelement_854]
text=Start of<br>Sheep Herder
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_60,0,0
condition2=varplayerbit_697,98,98

[mapelement_855]
text=Start of<br>Shilo Village
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_116,0,0
condition2=varplayerbit_697,99,99

[mapelement_856]
text=Start of<br>A Soul's Bane
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2011,0,0
condition2=varplayerbit_697,100,100

[mapelement_857]
text=Start of<br>Spirits of the Elid
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1444,0,0
condition2=varplayerbit_697,101,101

[mapelement_858]
text=Start of<br>Swan Song
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2098,0,0
condition2=varplayerbit_697,102,102

[mapelement_859]
text=Start of<br>Tai Bwo Wannai Trio
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_320,0,2
condition2=varplayerbit_697,103,103

[mapelement_860]
text=Start of<br>A Tail of Two Cats
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1028,0,0
condition2=varplayerbit_697,104,104

[mapelement_861]
text=Start of<br>Tears of Guthix
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_451,0,0
condition2=varplayerbit_697,105,105

[mapelement_862]
text=Route to<br>Tears of Guthix
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_451,0,0
condition2=varplayerbit_697,105,105

[mapelement_863]
text=Start of<br>Temple of Ikov
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_26,0,0
condition2=varplayerbit_697,106,106

[mapelement_864]
text=Start of<br>Throne of Miscellania
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_359,0,0
condition2=varplayerbit_697,107,107

[mapelement_865]
text=Start of<br>The Tourist Trap
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_197,0,0
condition2=varplayerbit_697,108,108

[mapelement_866]
text=Start of<br>Witch's House
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_226,0,0
condition2=varplayerbit_697,109,109

[mapelement_867]
text=Start of<br>Tree Gnome Village
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_111,0,0
condition2=varplayerbit_697,110,110

[mapelement_868]
text=Start of<br>Tribal Totem
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_200,0,0
condition2=varplayerbit_697,111,111

[mapelement_869]
text=Start of<br>Troll Romance
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_385,0,0
condition2=varplayerbit_697,112,112

[mapelement_870]
text=Route to<br>Troll Romance
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_385,0,0
condition2=varplayerbit_697,112,112

[mapelement_871]
text=Start of<br>Troll Stronghold
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_317,0,0
condition2=varplayerbit_697,113,113

[mapelement_872]
text=Start of<br>Wanted!
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1051,0,0
condition2=varplayerbit_697,115,115

[mapelement_873]
text=Start of<br>Watchtower
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_212,0,0
condition2=varplayerbit_697,116,116

[mapelement_874]
text=Start of<br>Cold War
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3293,0,0
condition2=varplayerbit_697,117,117

[mapelement_875]
text=Start of<br>The Fremennik Isles
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3311,0,0
condition2=varplayerbit_697,118,118

[mapelement_876]
text=Start of<br>Tower of Life
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3337,0,0
condition2=varplayerbit_697,119,119

[mapelement_877]
text=Start of<br>The Great Brain Robbery
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayer_980,0,0
condition2=varplayerbit_697,120,120

[mapelement_878]
text=Start of<br>What Lies Below
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3523,0,0
condition2=varplayerbit_697,121,121

[mapelement_879]
text=Start of<br>Olaf's Quest
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3534,0,0
condition2=varplayerbit_697,122,122

[mapelement_880]
text=Start of<br>Another Slice of H.A.M.
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3550,0,0
condition2=varplayerbit_697,123,123

[mapelement_881]
text=Route to<br>Another Slice of H.A.M.
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3550,0,0
condition2=varplayerbit_697,123,123

[mapelement_882]
text=Start of<br>Dream Mentor
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3618,0,0
condition2=varplayerbit_697,124,124

[mapelement_883]
text=Route to<br>Dream Mentor
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3618,0,0
condition2=varplayerbit_697,124,124

[mapelement_884]
text=Start of<br>Grim Tales
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_2783,0,0
condition2=varplayerbit_697,125,125

[mapelement_885]
text=Start of<br>King's Ransom
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3888,0,0
condition2=varplayerbit_697,126,126

[mapelement_886]
text=Start of<br>The Path of Glouphrie
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_3954,0,0
condition2=varplayerbit_697,127,127

[mapelement_887]
text=Start of<br>Back to my Roots
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4055,0,0
condition2=varplayerbit_697,128,128

[mapelement_888]
text=Start of<br>Land of the Goblins
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4105,0,0
condition2=varplayerbit_697,129,129

[mapelement_889]
text=Route to<br>Land of the Goblins
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4105,0,0
condition2=varplayerbit_697,129,129

[mapelement_890]
text=Start of<br>Dealing with Scabaras
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4230,0,0
condition2=varplayerbit_697,130,130

[mapelement_891]
text=Start of<br>Wolf Whistle
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4302,0,0
condition2=varplayerbit_697,131,131

[mapelement_892]
text=Start of<br>As a First Resort
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4321,0,9
condition2=varplayerbit_697,132,132

[mapelement_893]
text=Start of<br>Catapult Construction
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4396,0,0
condition2=varplayerbit_697,133,133

[mapelement_894]
text=Start of<br>Kennith's Concerns
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4505,0,0
condition2=varplayerbit_697,134,134

[mapelement_895]
text=Start of<br>Legacy of Seergaze
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4569,0,0
condition2=varplayerbit_697,135,135

[mapelement_896]
text=Start of<br>Perils of Ice Mountain
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4684,0,0
condition2=varplayerbit_697,136,136

[mapelement_897]
text=Start of<br>TokTz-Ket-Dill
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4700,0,0
condition2=varplayerbit_697,137,137

[mapelement_898]
text=Route to<br>TokTz-Ket-Dill
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4700,0,0
condition2=varplayerbit_697,137,137

[mapelement_899]
text=Start of<br>Smoking Kills
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4764,0,0
condition2=varplayerbit_697,138,138

[mapelement_900]
text=Start of<br>Rocking Out
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_4797,0,0
condition2=varplayerbit_697,139,139

[mapelement_901]
text=Start of<br>Spirit of Summer
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5032,0,0
condition2=varplayerbit_697,140,140

[mapelement_902]
text=Start of<br>Meeting History
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5075,0,0
condition2=varplayerbit_697,141,141

[mapelement_903]
text=Start of<br>All Fired Up
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5133,0,0
condition2=varplayerbit_697,142,142

[mapelement_904]
text=Start of<br>Summer's End
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5331,0,0
condition2=varplayerbit_697,143,143

[mapelement_905]
text=Start of<br>Defender of Varrock
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5387,0,0
condition2=varplayerbit_697,144,144

[mapelement_906]
text=Start of<br>While Guthix Sleeps
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5491,0,0
condition2=varplayerbit_697,145,145

[mapelement_907]
text=Start of<br>In Pyre Need
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5761,0,0
condition2=varplayerbit_697,146,146

[mapelement_908]
text=Start of<br>Myths of the White Lands
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5733,0,0
condition2=varplayerbit_697,148,148

[mapelement_909]
text=Start of<br>Glorious Memories
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6001,0,2
condition2=varplayerbit_697,149,149

[mapelement_910]
text=Start of<br>The Tale of the Muspah
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6048,0,5
condition2=varplayerbit_697,150,150

[mapelement_911]
text=Start of<br>Missing My Mummy
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6112,0,0
condition2=varplayerbit_697,155,155

[mapelement_912]
text=Start of<br>The Curse of Arrav
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6289,0,0
condition2=varplayerbit_697,156,156

[mapelement_913]
text=Start of<br>The Temple at Senntisten
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6775,0,0
condition2=varplayerbit_697,157,157

[mapelement_914]
text=Start of<br>Hunt for Red Raktuber
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6180,0,1
condition2=varplayerbit_697,151,151

[mapelement_915]
text=Start of<br>The Chosen Commander
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1938,0,0
condition2=varplayerbit_697,152,152

[mapelement_916]
text=Route to<br>The Chosen Commander
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_1938,0,0
condition2=varplayerbit_697,152,152

[mapelement_917]
text=Start of<br>Swept Away
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_5448,0,0
condition2=varplayerbit_697,153,153

[mapelement_918]
text=Start of<br>Nomad's Requiem
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6962,0,0
condition2=varplayerbit_697,162,162

[mapelement_919]
text=Start of<br>Blood Runs Deep
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_6883,0,1
condition2=varplayerbit_697,163,163

[mapelement_920]
sprite="mapdots_interface,0"
mapfunction=no
show=minimap

[mapelement_921]
text=Start of<br>The Blood Pact
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7238,0,0
condition2=varplayerbit_697,170,170

[mapelement_922]
text=Daemonheim
textsize=0
textcolour=0xffffff
mapfunction=yes
category=category_950

[mapelement_923]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7792,0,0
polygonpoint0=-12,39
polygonpoint1=33,39
polygonpoint2=33,71
polygonpoint3=-12,71
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_924]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7792,5,5
polygonpoint0=19,-2
polygonpoint1=28,-2
polygonpoint2=28,6
polygonpoint3=19,6
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_925]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7793,7,25
polygonpoint0=-3,1
polygonpoint1=-3,37
polygonpoint2=31,37
polygonpoint3=31,1
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_926]
mapfunction=no
show=both
condition=varplayerbit_6913,167,167
condition2=varplayerbit_7793,10,25
polygonpoint0=-1,8
polygonpoint1=-1,20
polygonpoint2=13,20
polygonpoint3=13,8
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_927]
text=Start of<br>Buyers and Cellars
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7792,0,0
condition2=varplayerbit_697,167,167

[mapelement_928]
text=Start of<br>Elemental Workshop III
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7871,0,0
condition2=varplayerbit_697,172,172

[mapelement_929]
show=both
condition=varplayerbit_6913,172,172
condition2=varplayerbit_7871,0,4
polygonpoint0=-10,10
polygonpoint1=10,10
polygonpoint2=10,-30
polygonpoint3=-10,-30
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_930]
text=Start of<br>Fairy Tale III
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7826,0,0
condition2=varplayerbit_697,158,158

[mapelement_931]
text=Start of<br>Quiet Before the Swarm
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7958,0,0
condition2=varplayerbit_697,171,171

[mapelement_932]
mapfunction=no
show=both
condition=varplayerbit_6913,170,170
condition2=varplayerbit_7238,1,59
polygonpoint0=-6,-8
polygonpoint1=-6,6
polygonpoint2=8,6
polygonpoint3=8,-8
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_933]
show=both
condition=varplayerbit_6913,171,171
condition2=varplayerbit_7958,5,85
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_934]
show=both
condition=varplayerbit_6913,171,171
condition2=varplayerbit_7958,5,85
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_935]
show=both
condition=varplayerbit_6913,171,171
condition2=varplayerbit_7958,0,85
polygonpoint0=-10,-15
polygonpoint1=-20,-5
polygonpoint2=-20,15
polygonpoint3=-10,20
polygonpoint4=10,20
polygonpoint5=20,15
polygonpoint6=20,-5
polygonpoint7=10,-15
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_936]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_937]
mapfunction=no
show=both
condition=varplayerbit_6913,153,153
condition2=varplayerbit_5448,1,49
polygonpoint0=-8,-5
polygonpoint1=-8,5
polygonpoint2=8,5
polygonpoint3=8,-5
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_938]
mapfunction=no
show=both
condition=varplayerbit_6913,153,153
condition2=varplayerbit_5448,20,29
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=8,8
polygonpoint3=8,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_939]
mapfunction=no
show=both
condition=varplayerbit_6913,153,153
condition2=varplayerbit_5448,20,29
polygonpoint0=0,0
polygonpoint1=0,10
polygonpoint2=8,10
polygonpoint3=8,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_940]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,1,9
polygonpoint0=0,0
polygonpoint1=0,7
polygonpoint2=7,7
polygonpoint3=7,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_941]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,50,59
polygonpoint0=0,0
polygonpoint1=0,7
polygonpoint2=7,7
polygonpoint3=7,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_942]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,10,49
polygonpoint0=0,0
polygonpoint1=0,8
polygonpoint2=9,8
polygonpoint3=9,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_943]
mapfunction=no
show=both
condition=varplayerbit_6913,148,148
condition2=varplayerbit_5733,10,49
polygonpoint0=0,0
polygonpoint1=0,9
polygonpoint2=11,9
polygonpoint3=11,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_944]
mapfunction=no
show=both
condition=varplayerbit_6913,168,168
condition2=varplayerbit_8045,55,124
polygonpoint0=17,0
polygonpoint1=17,-16
polygonpoint2=0,-16
polygonpoint3=0,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_945]
text=Start of<br>Love Story
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_8045,0,0
condition2=varplayerbit_697,168,168

[mapelement_946]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_947]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_948]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_949]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_950]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_951]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

[mapelement_952]
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,1,1
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_953]
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,60,60
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_954]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,3,15
polygonpoint0=20,-10
polygonpoint1=5,5
polygonpoint2=5,50
polygonpoint3=20,65
polygonpoint4=50,65
polygonpoint5=65,50
polygonpoint6=65,5
polygonpoint7=50,-10
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_955]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,16,24
polygonpoint0=-30,0
polygonpoint1=40,0
polygonpoint2=40,23
polygonpoint3=17,42
polygonpoint4=-14,46
polygonpoint5=-30,41
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_956]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,27,30
polygonpoint0=-24,20
polygonpoint1=-24,0
polygonpoint2=-3,0
polygonpoint3=-3,-3
polygonpoint4=10,-3
polygonpoint5=10,20
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_957]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,33,48
polygonpoint0=-4,5
polygonpoint1=-13,-1
polygonpoint2=-14,-13
polygonpoint3=7,-27
polygonpoint4=33,-27
polygonpoint5=32,-13
polygonpoint6=20,-7
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_958]
mapfunction=no
show=both
condition=varplayerbit_6913,173,173
condition2=varplayerbit_7451,51,57
polygonpoint0=-6,0
polygonpoint1=-6,22
polygonpoint2=16,22
polygonpoint3=16,0
polygonfill=0xff00ffff
polygonoutline=0x33aeffff

[mapelement_959]
text=Start of<br>A Void Dance
textcolour=0x95c8ff
textsize=0
textbackgroundoutline=0xffaf7d0f
textbackgroundfill=0xffffffc8
sprite="you_are_here_icon,3"
category=category_1399
condition=varplayerbit_7451,1,1
condition2=varplayerbit_697,173,173

[mapelement_960]
sprite="mapfunction_sep,70"
category=category_1217
mapfunction=yes
show=both

